// Generated by CIRCT firtool-1.62.0
module ALU(	// src/main/scala/components/ALU.scala:26:7
  input         clock,	// src/main/scala/components/ALU.scala:26:7
                reset,	// src/main/scala/components/ALU.scala:26:7
  input  [31:0] io_instruction,	// src/main/scala/components/ALU.scala:27:16
  input  [63:0] io_rj,	// src/main/scala/components/ALU.scala:27:16
                io_rk,	// src/main/scala/components/ALU.scala:27:16
                io_rd_in,	// src/main/scala/components/ALU.scala:27:16
                io_imm,	// src/main/scala/components/ALU.scala:27:16
  output [63:0] io_rd	// src/main/scala/components/ALU.scala:27:16
);

  assign io_rd = 64'h0;	// src/main/scala/components/ALU.scala:26:7, :33:33
endmodule

