// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module REG(	// src/main/scala/stages/REG.scala:18:7
  input         clock,	// src/main/scala/stages/REG.scala:18:7
                reset,	// src/main/scala/stages/REG.scala:18:7
  input  [4:0]  io_raddr1,	// src/main/scala/stages/REG.scala:19:16
                io_raddr2,	// src/main/scala/stages/REG.scala:19:16
  output [31:0] io_rdata1,	// src/main/scala/stages/REG.scala:19:16
                io_rdata2,	// src/main/scala/stages/REG.scala:19:16
  input         io_we,	// src/main/scala/stages/REG.scala:19:16
  input  [4:0]  io_waddr,	// src/main/scala/stages/REG.scala:19:16
  input  [31:0] io_wdata	// src/main/scala/stages/REG.scala:19:16
);

  reg  [31:0]       rf_0;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_1;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_2;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_3;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_4;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_5;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_6;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_7;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_8;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_9;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_10;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_11;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_12;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_13;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_14;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_15;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_16;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_17;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_18;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_19;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_20;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_21;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_22;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_23;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_24;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_25;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_26;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_27;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_28;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_29;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_30;	// src/main/scala/stages/REG.scala:21:21
  reg  [31:0]       rf_31;	// src/main/scala/stages/REG.scala:21:21
  wire [31:0][31:0] _GEN =
    {{rf_31},
     {rf_30},
     {rf_29},
     {rf_28},
     {rf_27},
     {rf_26},
     {rf_25},
     {rf_24},
     {rf_23},
     {rf_22},
     {rf_21},
     {rf_20},
     {rf_19},
     {rf_18},
     {rf_17},
     {rf_16},
     {rf_15},
     {rf_14},
     {rf_13},
     {rf_12},
     {rf_11},
     {rf_10},
     {rf_9},
     {rf_8},
     {rf_7},
     {rf_6},
     {rf_5},
     {rf_4},
     {rf_3},
     {rf_2},
     {rf_1},
     {rf_0}};	// src/main/scala/stages/REG.scala:21:21, :27:21
  always @(posedge clock) begin	// src/main/scala/stages/REG.scala:18:7
    if (reset) begin	// src/main/scala/stages/REG.scala:18:7
      rf_0 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_1 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_2 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_3 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_4 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_5 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_6 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_7 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_8 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_9 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_10 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_11 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_12 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_13 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_14 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_15 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_16 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_17 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_18 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_19 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_20 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_21 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_22 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_23 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_24 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_25 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_26 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_27 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_28 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_29 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_30 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
      rf_31 <= 32'h0;	// src/main/scala/stages/REG.scala:21:{21,29}
    end
    else begin	// src/main/scala/stages/REG.scala:18:7
      automatic logic _GEN_0 = io_we & (|io_waddr);	// src/main/scala/stages/REG.scala:23:{16,28}
      if (_GEN_0 & ~(|io_waddr))	// src/main/scala/stages/REG.scala:21:21, :23:{16,28,37}, :24:22
        rf_0 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h1)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_1 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h2)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_2 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h3)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_3 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h4)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_4 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h5)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_5 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h6)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_6 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h7)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_7 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h8)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_8 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h9)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_9 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'hA)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_10 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'hB)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_11 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'hC)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_12 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'hD)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_13 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'hE)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_14 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'hF)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_15 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h10)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_16 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h11)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_17 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h12)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_18 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h13)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_19 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h14)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_20 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h15)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_21 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h16)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_22 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h17)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_23 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h18)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_24 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h19)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_25 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h1A)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_26 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h1B)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_27 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h1C)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_28 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h1D)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_29 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h1E)	// src/main/scala/stages/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_30 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
      if (_GEN_0 & (&io_waddr))	// src/main/scala/stages/REG.scala:21:21, :23:{16,37}, :24:22
        rf_31 <= io_wdata;	// src/main/scala/stages/REG.scala:21:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/stages/REG.scala:18:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/REG.scala:18:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/REG.scala:18:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/stages/REG.scala:18:7
      automatic logic [31:0] _RANDOM[0:31];	// src/main/scala/stages/REG.scala:18:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/stages/REG.scala:18:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/stages/REG.scala:18:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/stages/REG.scala:18:7
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          _RANDOM[i[4:0]] = `RANDOM;	// src/main/scala/stages/REG.scala:18:7
        end	// src/main/scala/stages/REG.scala:18:7
        rf_0 = _RANDOM[5'h0];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_1 = _RANDOM[5'h1];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_2 = _RANDOM[5'h2];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_3 = _RANDOM[5'h3];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_4 = _RANDOM[5'h4];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_5 = _RANDOM[5'h5];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_6 = _RANDOM[5'h6];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_7 = _RANDOM[5'h7];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_8 = _RANDOM[5'h8];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_9 = _RANDOM[5'h9];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_10 = _RANDOM[5'hA];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_11 = _RANDOM[5'hB];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_12 = _RANDOM[5'hC];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_13 = _RANDOM[5'hD];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_14 = _RANDOM[5'hE];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_15 = _RANDOM[5'hF];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_16 = _RANDOM[5'h10];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_17 = _RANDOM[5'h11];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_18 = _RANDOM[5'h12];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_19 = _RANDOM[5'h13];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_20 = _RANDOM[5'h14];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_21 = _RANDOM[5'h15];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_22 = _RANDOM[5'h16];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_23 = _RANDOM[5'h17];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_24 = _RANDOM[5'h18];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_25 = _RANDOM[5'h19];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_26 = _RANDOM[5'h1A];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_27 = _RANDOM[5'h1B];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_28 = _RANDOM[5'h1C];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_29 = _RANDOM[5'h1D];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_30 = _RANDOM[5'h1E];	// src/main/scala/stages/REG.scala:18:7, :21:21
        rf_31 = _RANDOM[5'h1F];	// src/main/scala/stages/REG.scala:18:7, :21:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/stages/REG.scala:18:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/stages/REG.scala:18:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rdata1 = io_raddr1 == 5'h0 ? 32'h0 : _GEN[io_raddr1];	// src/main/scala/stages/REG.scala:18:7, :21:29, :27:{21,32}
  assign io_rdata2 = io_raddr2 == 5'h0 ? 32'h0 : _GEN[io_raddr2];	// src/main/scala/stages/REG.scala:18:7, :21:29, :27:21, :28:{21,32}
endmodule

module ID(	// src/main/scala/stages/ID.scala:122:7
  input          clock,	// src/main/scala/stages/ID.scala:122:7
                 reset,	// src/main/scala/stages/ID.scala:122:7
                 io_es_allowin,	// src/main/scala/stages/ID.scala:123:16
  output         io_ds_allowin,	// src/main/scala/stages/ID.scala:123:16
  input          io_fs_to_ds_valid,	// src/main/scala/stages/ID.scala:123:16
  input  [63:0]  io_fs_to_ds_bus,	// src/main/scala/stages/ID.scala:123:16
  input  [37:0]  io_ws_to_rf_bus,	// src/main/scala/stages/ID.scala:123:16
  output         io_ds_to_es_valid,	// src/main/scala/stages/ID.scala:123:16
  output [145:0] io_ds_to_es_bus,	// src/main/scala/stages/ID.scala:123:16
  output [32:0]  io_br_bus	// src/main/scala/stages/ID.scala:123:16
);

  wire [31:0] _u_regfile_io_rdata1;	// src/main/scala/stages/ID.scala:205:27
  wire [31:0] _u_regfile_io_rdata2;	// src/main/scala/stages/ID.scala:205:27
  reg  [63:0] fs_to_ds_bus_r;	// src/main/scala/stages/ID.scala:126:33
  reg         ds_valid;	// src/main/scala/stages/ID.scala:127:27
  wire        io_ds_allowin_0 = ~ds_valid | io_es_allowin;	// src/main/scala/stages/ID.scala:127:27, :129:{22,32}
  wire        _GEN = fs_to_ds_bus_r[63:47] == 17'h20;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_0 = fs_to_ds_bus_r[63:47] == 17'h22;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_1 = fs_to_ds_bus_r[63:47] == 17'h24;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_2 = fs_to_ds_bus_r[63:47] == 17'h25;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_3 = fs_to_ds_bus_r[63:47] == 17'h28;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_4 = fs_to_ds_bus_r[63:47] == 17'h29;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_5 = fs_to_ds_bus_r[63:47] == 17'h2A;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_6 = fs_to_ds_bus_r[63:47] == 17'h2B;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_7 = fs_to_ds_bus_r[63:47] == 17'h81;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_8 = fs_to_ds_bus_r[63:47] == 17'h89;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_9 = fs_to_ds_bus_r[63:47] == 17'h91;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_10 = fs_to_ds_bus_r[63:54] == 10'hA;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_11 = fs_to_ds_bus_r[63:54] == 10'hA2;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_12 = fs_to_ds_bus_r[63:54] == 10'hA6;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_13 = fs_to_ds_bus_r[63:58] == 6'hD;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_14 = fs_to_ds_bus_r[63:58] == 6'hE;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_15 = fs_to_ds_bus_r[63:58] == 6'hF;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_16 = fs_to_ds_bus_r[63:57] == 7'hA;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33
  wire        _GEN_17 = fs_to_ds_bus_r[63:58] == 6'h10 | fs_to_ds_bus_r[63:58] == 6'h11;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/stages/ID.scala:126:33, :139:33
  wire [3:0]  instType =
    _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6
      ? 4'h3
      : _GEN_7 | _GEN_8 | _GEN_9
          ? 4'h9
          : _GEN_10 | _GEN_11 | _GEN_12
              ? 4'h1
              : _GEN_13
                  ? 4'h6
                  : _GEN_14 | _GEN_15 ? 4'h8 : {1'h0, _GEN_17 ? 3'h6 : {_GEN_16, 2'h3}};	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/stages/ID.scala:122:7, :127:27
  wire        rj_eq_rd = _u_regfile_io_rdata1 == _u_regfile_io_rdata2;	// src/main/scala/stages/ID.scala:205:27, :216:30
  always @(posedge clock) begin	// src/main/scala/stages/ID.scala:122:7
    if (reset) begin	// src/main/scala/stages/ID.scala:122:7
      fs_to_ds_bus_r <= 64'h0;	// src/main/scala/stages/ID.scala:126:33
      ds_valid <= 1'h0;	// src/main/scala/stages/ID.scala:127:27
    end
    else begin	// src/main/scala/stages/ID.scala:122:7
      if (io_fs_to_ds_valid & io_ds_allowin_0)	// src/main/scala/stages/ID.scala:129:32, :134:29
        fs_to_ds_bus_r <= io_fs_to_ds_bus;	// src/main/scala/stages/ID.scala:126:33
      if (io_ds_allowin_0)	// src/main/scala/stages/ID.scala:129:32
        ds_valid <= io_fs_to_ds_valid;	// src/main/scala/stages/ID.scala:127:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/stages/ID.scala:122:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/ID.scala:122:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/ID.scala:122:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/stages/ID.scala:122:7
      automatic logic [31:0] _RANDOM[0:2];	// src/main/scala/stages/ID.scala:122:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/stages/ID.scala:122:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/stages/ID.scala:122:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/stages/ID.scala:122:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/stages/ID.scala:122:7
        end	// src/main/scala/stages/ID.scala:122:7
        fs_to_ds_bus_r = {_RANDOM[2'h0], _RANDOM[2'h1]};	// src/main/scala/stages/ID.scala:122:7, :126:33
        ds_valid = _RANDOM[2'h2][0];	// src/main/scala/stages/ID.scala:122:7, :127:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/stages/ID.scala:122:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/stages/ID.scala:122:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  REG u_regfile (	// src/main/scala/stages/ID.scala:205:27
    .clock     (clock),
    .reset     (reset),
    .io_raddr1 (fs_to_ds_bus_r[41:37]),	// src/main/scala/stages/ID.scala:126:33, :139:33, :144:23
    .io_raddr2
      (fs_to_ds_bus_r[63:58] == 6'h10 | fs_to_ds_bus_r[63:58] == 6'h11
       | fs_to_ds_bus_r[63:54] == 10'hA6
         ? fs_to_ds_bus_r[36:32]
         : fs_to_ds_bus_r[46:42]),	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/stages/ID.scala:126:33, :139:33, :143:23, :145:23, :167:34, :168:34, :169:{23,34}, :197:24
    .io_rdata1 (_u_regfile_io_rdata1),
    .io_rdata2 (_u_regfile_io_rdata2),
    .io_we     (io_ws_to_rf_bus[37]),	// src/main/scala/stages/ID.scala:200:32
    .io_waddr  (io_ws_to_rf_bus[36:32]),	// src/main/scala/stages/ID.scala:201:35
    .io_wdata  (io_ws_to_rf_bus[31:0])	// src/main/scala/stages/ID.scala:202:35
  );
  assign io_ds_allowin = io_ds_allowin_0;	// src/main/scala/stages/ID.scala:122:7, :129:32
  assign io_ds_to_es_valid = ds_valid;	// src/main/scala/stages/ID.scala:122:7, :127:27
  assign io_ds_to_es_bus =
    {_GEN
       ? 6'h20
       : _GEN_0
           ? 6'h21
           : _GEN_1
               ? 6'h22
               : _GEN_2
                   ? 6'h23
                   : _GEN_3
                       ? 6'h25
                       : _GEN_4
                           ? 6'h24
                           : _GEN_5
                               ? 6'h26
                               : _GEN_6
                                   ? 6'h27
                                   : _GEN_7
                                       ? 6'h28
                                       : _GEN_8
                                           ? 6'h29
                                           : _GEN_9
                                               ? 6'h2A
                                               : _GEN_10 | _GEN_11 | _GEN_12 | _GEN_13
                                                   ? 6'h20
                                                   : _GEN_14
                                                       ? 6'h0
                                                       : _GEN_15
                                                           ? 6'h20
                                                           : _GEN_17
                                                               ? 6'h0
                                                               : _GEN_16 ? 6'h2B : 6'h20,
     1'h0,
     fs_to_ds_bus_r[63:58] == 6'hD | fs_to_ds_bus_r[63:58] == 6'hF,
     fs_to_ds_bus_r[63:47] == 17'h81 | fs_to_ds_bus_r[63:47] == 17'h89
       | fs_to_ds_bus_r[63:47] == 17'h91 | fs_to_ds_bus_r[63:54] == 10'hA
       | fs_to_ds_bus_r[63:54] == 10'hA2 | fs_to_ds_bus_r[63:54] == 10'hA6
       | fs_to_ds_bus_r[63:57] == 7'hA | fs_to_ds_bus_r[63:58] == 6'hD
       | fs_to_ds_bus_r[63:58] == 6'hF,
     fs_to_ds_bus_r[63:58] == 6'hD | fs_to_ds_bus_r[63:58] == 6'hF,
     fs_to_ds_bus_r[63:54] != 10'hA6 & fs_to_ds_bus_r[63:58] != 6'h10
       & fs_to_ds_bus_r[63:58] != 6'h11 & fs_to_ds_bus_r[63:58] != 6'hE,
     fs_to_ds_bus_r[63:54] == 10'hA6,
     fs_to_ds_bus_r[63:58] == 6'hF ? 5'h1 : fs_to_ds_bus_r[36:32],
     instType == 4'h9
       ? {27'h0, fs_to_ds_bus_r[46:42]}
       : instType == 4'h7
           ? {fs_to_ds_bus_r[56:37], 12'h0}
           : instType == 4'h1 ? {{20{fs_to_ds_bus_r[53]}}, fs_to_ds_bus_r[53:42]} : 32'h4,
     _u_regfile_io_rdata1,
     _u_regfile_io_rdata2,
     fs_to_ds_bus_r[31:0],
     fs_to_ds_bus_r[63:54] == 10'hA2};	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/config/Configs.scala:14:{28,43}, :15:16, :59:32, src/main/scala/stages/ID.scala:122:7, :126:33, :127:27, :139:33, :140:31, :143:23, :145:23, :146:23, :147:23, :157:{25,35}, :171:31, :172:{20,31}, :174:32, :175:32, :176:32, :177:32, :178:32, :179:32, :180:32, :181:32, :182:{21,32}, :184:30, :185:{18,29}, :187:33, :188:33, :189:33, :190:33, :191:{33,54}, :192:33, :193:33, :194:27, :205:27, :234:27
  assign io_br_bus =
    {(fs_to_ds_bus_r[63:58] == 6'h10 & rj_eq_rd | fs_to_ds_bus_r[63:58] == 6'h11
      & ~rj_eq_rd | fs_to_ds_bus_r[63:58] == 6'hD | fs_to_ds_bus_r[63:58] == 6'hF
      | fs_to_ds_bus_r[63:58] == 6'hE) & ds_valid,
     fs_to_ds_bus_r[63:58] == 6'h10 | fs_to_ds_bus_r[63:58] == 6'h11
     | fs_to_ds_bus_r[63:58] == 6'hE | fs_to_ds_bus_r[63:58] == 6'hF
       ? fs_to_ds_bus_r[31:0]
         + {instType == 4'h8
              ? {{4{fs_to_ds_bus_r[41]}}, fs_to_ds_bus_r[41:32]}
              : {14{fs_to_ds_bus_r[57]}},
            fs_to_ds_bus_r[57:42],
            2'h0}
       : _u_regfile_io_rdata1 + {{14{fs_to_ds_bus_r[57]}}, fs_to_ds_bus_r[57:42], 2'h0}};	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/config/Configs.scala:14:{28,43}, :15:16, src/main/scala/stages/ID.scala:122:7, :126:33, :127:27, :139:33, :140:31, :148:23, :149:27, :162:{22,32}, :205:27, :216:30, :217:{29,50}, :218:{29,50,53}, :219:29, :220:29, :221:{18,29,49}, :223:{24,34}, :224:34, :225:34, :226:{23,34}, :227:32, :228:35, :230:21
endmodule

