// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Reg(	// src/main/scala/CPU/IDstage/Reg.scala:19:7
  input         clock,	// src/main/scala/CPU/IDstage/Reg.scala:19:7
                reset,	// src/main/scala/CPU/IDstage/Reg.scala:19:7
  input  [4:0]  io_raddr1,	// src/main/scala/CPU/IDstage/Reg.scala:20:16
                io_raddr2,	// src/main/scala/CPU/IDstage/Reg.scala:20:16
  output [63:0] io_rdata1,	// src/main/scala/CPU/IDstage/Reg.scala:20:16
                io_rdata2,	// src/main/scala/CPU/IDstage/Reg.scala:20:16
  input         io_rf_bus_valid,	// src/main/scala/CPU/IDstage/Reg.scala:20:16
  input  [4:0]  io_rf_bus_waddr,	// src/main/scala/CPU/IDstage/Reg.scala:20:16
  input  [63:0] io_rf_bus_wdata	// src/main/scala/CPU/IDstage/Reg.scala:20:16
);

  reg  [31:0]       reg_0;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_1;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_2;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_3;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_4;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_5;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_6;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_7;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_8;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_9;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_10;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_11;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_12;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_13;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_14;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_15;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_16;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_17;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_18;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_19;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_20;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_21;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_22;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_23;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_24;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_25;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_26;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_27;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_28;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_29;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_30;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  reg  [31:0]       reg_31;	// src/main/scala/CPU/IDstage/Reg.scala:22:22
  wire [31:0][31:0] _GEN =
    {{reg_31},
     {reg_30},
     {reg_29},
     {reg_28},
     {reg_27},
     {reg_26},
     {reg_25},
     {reg_24},
     {reg_23},
     {reg_22},
     {reg_21},
     {reg_20},
     {reg_19},
     {reg_18},
     {reg_17},
     {reg_16},
     {reg_15},
     {reg_14},
     {reg_13},
     {reg_12},
     {reg_11},
     {reg_10},
     {reg_9},
     {reg_8},
     {reg_7},
     {reg_6},
     {reg_5},
     {reg_4},
     {reg_3},
     {reg_2},
     {reg_1},
     {reg_0}};	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :28:21
  always @(posedge clock) begin	// src/main/scala/CPU/IDstage/Reg.scala:19:7
    if (reset) begin	// src/main/scala/CPU/IDstage/Reg.scala:19:7
      reg_0 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_1 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_2 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_3 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_4 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_5 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_6 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_7 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_8 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_9 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_10 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_11 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_12 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_13 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_14 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_15 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_16 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_17 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_18 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_19 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_20 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_21 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_22 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_23 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_24 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_25 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_26 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_27 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_28 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_29 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_30 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
      reg_31 <= 32'h0;	// src/main/scala/CPU/IDstage/Reg.scala:22:{22,30}
    end
    else begin	// src/main/scala/CPU/IDstage/Reg.scala:19:7
      automatic logic _GEN_0 = io_rf_bus_valid & (|io_rf_bus_waddr);	// src/main/scala/CPU/IDstage/Reg.scala:24:{26,45}
      if (_GEN_0 & ~(|io_rf_bus_waddr))	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :24:{26,45,54}, :25:30
        reg_0 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h1)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_1 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h2)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_2 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h3)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_3 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h4)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_4 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h5)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_5 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h6)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_6 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h7)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_7 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h8)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_8 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h9)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_9 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'hA)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_10 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'hB)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_11 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'hC)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_12 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'hD)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_13 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'hE)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_14 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'hF)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_15 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h10)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_16 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h11)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_17 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h12)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_18 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h13)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_19 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h14)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_20 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h15)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_21 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h16)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_22 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h17)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_23 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h18)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_24 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h19)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_25 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h1A)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_26 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h1B)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_27 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h1C)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_28 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h1D)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_29 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & io_rf_bus_waddr == 5'h1E)	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22, :24:{26,54}, :25:30
        reg_30 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
      if (_GEN_0 & (&io_rf_bus_waddr))	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :24:{26,54}, :25:30
        reg_31 <= io_rf_bus_wdata[31:0];	// src/main/scala/CPU/IDstage/Reg.scala:22:22, :25:30
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/CPU/IDstage/Reg.scala:19:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/CPU/IDstage/Reg.scala:19:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/CPU/IDstage/Reg.scala:19:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/CPU/IDstage/Reg.scala:19:7
      automatic logic [31:0] _RANDOM[0:31];	// src/main/scala/CPU/IDstage/Reg.scala:19:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/CPU/IDstage/Reg.scala:19:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/CPU/IDstage/Reg.scala:19:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/CPU/IDstage/Reg.scala:19:7
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          _RANDOM[i[4:0]] = `RANDOM;	// src/main/scala/CPU/IDstage/Reg.scala:19:7
        end	// src/main/scala/CPU/IDstage/Reg.scala:19:7
        reg_0 = _RANDOM[5'h0];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_1 = _RANDOM[5'h1];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_2 = _RANDOM[5'h2];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_3 = _RANDOM[5'h3];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_4 = _RANDOM[5'h4];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_5 = _RANDOM[5'h5];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_6 = _RANDOM[5'h6];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_7 = _RANDOM[5'h7];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_8 = _RANDOM[5'h8];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_9 = _RANDOM[5'h9];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_10 = _RANDOM[5'hA];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_11 = _RANDOM[5'hB];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_12 = _RANDOM[5'hC];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_13 = _RANDOM[5'hD];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_14 = _RANDOM[5'hE];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_15 = _RANDOM[5'hF];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_16 = _RANDOM[5'h10];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_17 = _RANDOM[5'h11];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_18 = _RANDOM[5'h12];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_19 = _RANDOM[5'h13];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_20 = _RANDOM[5'h14];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_21 = _RANDOM[5'h15];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_22 = _RANDOM[5'h16];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_23 = _RANDOM[5'h17];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_24 = _RANDOM[5'h18];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_25 = _RANDOM[5'h19];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_26 = _RANDOM[5'h1A];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_27 = _RANDOM[5'h1B];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_28 = _RANDOM[5'h1C];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_29 = _RANDOM[5'h1D];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_30 = _RANDOM[5'h1E];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
        reg_31 = _RANDOM[5'h1F];	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/CPU/IDstage/Reg.scala:19:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/CPU/IDstage/Reg.scala:19:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rdata1 = {32'h0, io_raddr1 == 5'h0 ? 32'h0 : _GEN[io_raddr1]};	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:30, :28:{15,21,32}
  assign io_rdata2 = {32'h0, io_raddr2 == 5'h0 ? 32'h0 : _GEN[io_raddr2]};	// src/main/scala/CPU/IDstage/Reg.scala:19:7, :22:30, :28:21, :29:{15,21,32}
endmodule

module IDtop(	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
  input         clock,	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
                reset,	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
  output        io_hand_shake_bf_ready_in,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  input         io_hand_shake_bf_valid_out,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  input  [31:0] io_hand_shake_bf_bus_out_pc,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
                io_hand_shake_bf_bus_out_inst,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  input  [1:0]  io_hand_shake_bf_bus_out_func_type,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  input  [9:0]  io_hand_shake_bf_bus_out_op_type,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  input  [63:0] io_hand_shake_bf_bus_out_src1,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
                io_hand_shake_bf_bus_out_src2,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
                io_hand_shake_bf_bus_out_imm,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  input         io_hand_shake_bf_bus_out_rf_bus_valid,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  input  [4:0]  io_hand_shake_bf_bus_out_rf_bus_waddr,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  input  [63:0] io_hand_shake_bf_bus_out_rf_bus_wdata,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
                io_hand_shake_bf_bus_out_alu_result,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  input         io_hand_shake_af_ready_in,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  output        io_hand_shake_af_valid_out,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  output [31:0] io_hand_shake_af_bus_out_pc,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
                io_hand_shake_af_bus_out_inst,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  output [1:0]  io_hand_shake_af_bus_out_func_type,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  output [9:0]  io_hand_shake_af_bus_out_op_type,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  output [63:0] io_hand_shake_af_bus_out_src1,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
                io_hand_shake_af_bus_out_src2,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
                io_hand_shake_af_bus_out_imm,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  output        io_hand_shake_af_bus_out_rf_bus_valid,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  output [4:0]  io_hand_shake_af_bus_out_rf_bus_waddr,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  output [63:0] io_hand_shake_af_bus_out_rf_bus_wdata,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
                io_hand_shake_af_bus_out_alu_result,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  input         io_rf_bus_valid,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  input  [4:0]  io_rf_bus_waddr,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  input  [63:0] io_rf_bus_wdata,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  output        io_br_bus_valid,	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
  output [31:0] io_br_bus_pc_target	// src/main/scala/CPU/IDstage/IDtop.scala:24:16
);

  wire [63:0] _reg_io_rdata1;	// src/main/scala/CPU/IDstage/IDtop.scala:52:21
  wire [63:0] _reg_io_rdata2;	// src/main/scala/CPU/IDstage/IDtop.scala:52:21
  reg         bus_valid;	// src/main/scala/CPU/Parameters/parameters.scala:34:28
  wire        io_hand_shake_bf_ready_in_0 = ~bus_valid | io_hand_shake_af_ready_in;	// src/main/scala/CPU/Parameters/parameters.scala:34:28, :36:{23,30}
  wire        _bus_T = io_hand_shake_bf_valid_out & io_hand_shake_bf_ready_in_0;	// src/main/scala/CPU/Parameters/parameters.scala:36:30, :41:27
  wire [31:0] bus_pc = _bus_T ? io_hand_shake_bf_bus_out_pc : 32'h0;	// src/main/scala/CPU/Parameters/parameters.scala:33:{27,40}, :41:{27,42}, :42:17
  wire        _GEN = io_hand_shake_bf_bus_out_inst[31:15] == 17'h20;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_0 = io_hand_shake_bf_bus_out_inst[31:15] == 17'h22;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_1 = io_hand_shake_bf_bus_out_inst[31:15] == 17'h24;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_2 = io_hand_shake_bf_bus_out_inst[31:15] == 17'h25;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_3 = io_hand_shake_bf_bus_out_inst[31:15] == 17'h28;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_4 = io_hand_shake_bf_bus_out_inst[31:15] == 17'h29;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_5 = io_hand_shake_bf_bus_out_inst[31:15] == 17'h2A;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_6 = io_hand_shake_bf_bus_out_inst[31:22] == 10'hE;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_7 = io_hand_shake_bf_bus_out_inst[31:15] == 17'h2B;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_8 = io_hand_shake_bf_bus_out_inst[31:15] == 17'h81;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_9 = io_hand_shake_bf_bus_out_inst[31:15] == 17'h89;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_10 = io_hand_shake_bf_bus_out_inst[31:15] == 17'h91;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_11 = io_hand_shake_bf_bus_out_inst[31:22] == 10'hA;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_12 = io_hand_shake_bf_bus_out_inst[31:22] == 10'hA2;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_13 = io_hand_shake_bf_bus_out_inst[31:22] == 10'hA6;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_14 = io_hand_shake_bf_bus_out_inst[31:26] == 6'hD;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_15 = io_hand_shake_bf_bus_out_inst[31:26] == 6'hE;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_16 = io_hand_shake_bf_bus_out_inst[31:26] == 6'hF;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_17 = io_hand_shake_bf_bus_out_inst[31:26] == 6'h10;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_18 = io_hand_shake_bf_bus_out_inst[31:26] == 6'h11;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_19 = io_hand_shake_bf_bus_out_inst[31:25] == 7'hA;	// src/main/scala/CPU/Parameters/parameters.scala:48:32, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire        _GEN_20 = _GEN_17 | _GEN_18;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire        _GEN_21 = _GEN_12 | _GEN_13;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [6:0]  inst_type =
    _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
      ? 7'h3
      : _GEN_6
          ? 7'h1
          : _GEN_7
              ? 7'h3
              : _GEN_8 | _GEN_9 | _GEN_10
                  ? 7'h9
                  : _GEN_11 | _GEN_21
                      ? 7'h1
                      : _GEN_14
                          ? 7'h26
                          : _GEN_15 | _GEN_16
                              ? 7'h48
                              : {1'h0, _GEN_20 ? 6'h26 : {1'h0, _GEN_19 ? 5'h7 : 5'h1F}};	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire        _GEN_22 = _GEN_14 | ~_GEN_15 & (_GEN_16 | ~_GEN_17 & ~_GEN_18);	// src/main/scala/CPU/Parameters/parameters.scala:33:40, :36:42, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [25:0] imm =
    inst_type == 7'h10
      ? {4'h0, io_hand_shake_bf_bus_out_inst[31:10]}
      : inst_type == 7'hA
          ? {20'h0, io_hand_shake_bf_bus_out_inst[15:10]}
          : inst_type == 7'h9
              ? {21'h0, io_hand_shake_bf_bus_out_inst[14:10]}
              : inst_type == 7'h48
                  ? {io_hand_shake_bf_bus_out_inst[9:0],
                     io_hand_shake_bf_bus_out_inst[25:10]}
                  : {4'h0,
                     inst_type == 7'h7
                       ? io_hand_shake_bf_bus_out_inst[26:5]
                       : {6'h0,
                          inst_type == 7'h26
                            ? io_hand_shake_bf_bus_out_inst[25:10]
                            : {2'h0,
                               inst_type == 7'h5
                                 ? io_hand_shake_bf_bus_out_inst[23:10]
                                 : {2'h0,
                                    inst_type == 7'h1
                                      ? io_hand_shake_bf_bus_out_inst[21:10]
                                      : {4'h0,
                                         inst_type == 7'h0
                                           ? io_hand_shake_bf_bus_out_inst[17:10]
                                           : 8'h0}}}}};	// src/main/scala/CPU/IDstage/IDtop.scala:35:25, :36:26, :37:26, :38:26, :39:26, :40:{25,30}, :41:26, :42:26, :43:26, src/main/scala/CPU/Parameters/parameters.scala:33:40, :48:32, src/main/scala/chisel3/util/Lookup.scala:34:39
  always @(posedge clock) begin	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
    if (reset)	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
      bus_valid <= 1'h0;	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, src/main/scala/CPU/Parameters/parameters.scala:34:28
    else if (io_hand_shake_bf_ready_in_0)	// src/main/scala/CPU/Parameters/parameters.scala:36:30
      bus_valid <= io_hand_shake_bf_valid_out;	// src/main/scala/CPU/Parameters/parameters.scala:34:28
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
      automatic logic [31:0] _RANDOM[0:0];	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
        bus_valid = _RANDOM[/*Zero width*/ 1'b0][0];	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, src/main/scala/CPU/Parameters/parameters.scala:34:28
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/CPU/IDstage/IDtop.scala:23:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Reg reg_0 (	// src/main/scala/CPU/IDstage/IDtop.scala:52:21
    .clock           (clock),
    .reset           (reset),
    .io_raddr1       (io_hand_shake_bf_bus_out_inst[9:5]),	// src/main/scala/CPU/IDstage/IDtop.scala:47:18
    .io_raddr2
      (io_hand_shake_bf_bus_out_inst[31:26] == 6'h10
       | io_hand_shake_bf_bus_out_inst[31:26] == 6'h11
       | io_hand_shake_bf_bus_out_inst[31:22] == 10'hA6
         ? io_hand_shake_bf_bus_out_inst[4:0]
         : io_hand_shake_bf_bus_out_inst[14:10]),	// src/main/scala/CPU/IDstage/IDtop.scala:41:26, :49:18, :55:{25,32}, :56:32, :57:{24,32}, src/main/scala/chisel3/util/Lookup.scala:31:38
    .io_rdata1       (_reg_io_rdata1),
    .io_rdata2       (_reg_io_rdata2),
    .io_rf_bus_valid (io_rf_bus_valid),
    .io_rf_bus_waddr (io_rf_bus_waddr),
    .io_rf_bus_wdata (io_rf_bus_wdata)
  );
  assign io_hand_shake_bf_ready_in = io_hand_shake_bf_ready_in_0;	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, src/main/scala/CPU/Parameters/parameters.scala:36:30
  assign io_hand_shake_af_valid_out = bus_valid;	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, src/main/scala/CPU/Parameters/parameters.scala:34:28
  assign io_hand_shake_af_bus_out_pc = bus_pc;	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, src/main/scala/CPU/Parameters/parameters.scala:33:27, :41:42, :42:17
  assign io_hand_shake_af_bus_out_inst = _bus_T ? io_hand_shake_bf_bus_out_inst : 32'h0;	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, src/main/scala/CPU/Parameters/parameters.scala:33:{27,40}, :41:{27,42}, :42:17
  assign io_hand_shake_af_bus_out_func_type =
    _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
    | _GEN_9 | _GEN_10 | _GEN_11
      ? 2'h1
      : _GEN_21 ? 2'h2 : {1'h0, _GEN_22};	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  assign io_hand_shake_af_bus_out_op_type =
    {4'h0,
     _GEN
       ? 6'h1
       : _GEN_0
           ? 6'h2
           : _GEN_1
               ? 6'h3
               : _GEN_2
                   ? 6'h4
                   : _GEN_3
                       ? 6'h6
                       : _GEN_4
                           ? 6'h5
                           : _GEN_5 | _GEN_6
                               ? 6'h7
                               : _GEN_7
                                   ? 6'h8
                                   : _GEN_8
                                       ? 6'h9
                                       : _GEN_9
                                           ? 6'hA
                                           : _GEN_10
                                               ? 6'hB
                                               : _GEN_11
                                                   ? 6'h1
                                                   : _GEN_12
                                                       ? 6'h0
                                                       : _GEN_13 | _GEN_14
                                                           ? 6'h1
                                                           : _GEN_15
                                                               ? 6'h0
                                                               : _GEN_16
                                                                   ? 6'h1
                                                                   : _GEN_20
                                                                       ? 6'h0
                                                                       : _GEN_19
                                                                           ? 6'hC
                                                                           : 6'h3F};	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, :79:25, src/main/scala/CPU/Parameters/parameters.scala:48:32, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  assign io_hand_shake_af_bus_out_src1 = _reg_io_rdata1;	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, :52:21
  assign io_hand_shake_af_bus_out_src2 = _reg_io_rdata2;	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, :52:21
  assign io_hand_shake_af_bus_out_imm = {38'h0, imm};	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, :82:21, src/main/scala/CPU/Parameters/parameters.scala:48:32
  assign io_hand_shake_af_bus_out_rf_bus_valid =
    _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7 | _GEN_8
    | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12 | ~_GEN_13 & _GEN_22;	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  assign io_hand_shake_af_bus_out_rf_bus_waddr =
    io_hand_shake_bf_bus_out_inst[31:26] == 6'hF
      ? 5'h1
      : io_hand_shake_bf_bus_out_inst[4:0];	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, :49:18, :75:{24,30}, src/main/scala/chisel3/util/Lookup.scala:31:38
  assign io_hand_shake_af_bus_out_rf_bus_wdata = 64'h0;	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, src/main/scala/CPU/Parameters/parameters.scala:33:40
  assign io_hand_shake_af_bus_out_alu_result =
    _bus_T ? io_hand_shake_bf_bus_out_alu_result : 64'h0;	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, src/main/scala/CPU/Parameters/parameters.scala:33:{27,40}, :41:{27,42}, :42:17
  assign io_br_bus_valid = |(inst_type[6:5]);	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, src/main/scala/CPU/ISA.scala:27:50, :28:61, src/main/scala/chisel3/util/Lookup.scala:34:39
  assign io_br_bus_pc_target =
    inst_type[6:5] == 2'h2
      ? bus_pc + {{4{imm[25]}}, imm, 2'h0}
      : inst_type[6:5] == 2'h1
          ? (io_hand_shake_bf_bus_out_inst[31:26] == 6'hD
               ? _reg_io_rdata1[31:0] + {{4{imm[25]}}, imm, 2'h0}
               : io_hand_shake_bf_bus_out_inst[31:26] == 6'h10
                 & _reg_io_rdata1 == _reg_io_rdata2
                 | io_hand_shake_bf_bus_out_inst[31:26] == 6'h11
                 & _reg_io_rdata1 != _reg_io_rdata2
                   ? bus_pc + {6'h0, imm}
                   : 32'h0)
          : 32'h0;	// src/main/scala/CPU/IDstage/IDtop.scala:23:7, :52:21, :65:{19,55}, :66:{19,40,52,77}, :67:{19,40,52}, :69:35, src/main/scala/CPU/ISA.scala:27:50, src/main/scala/CPU/Parameters/parameters.scala:33:{27,40}, :41:42, :42:17, :48:32, :52:24, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/chisel3/util/Mux.scala:126:16
endmodule

