// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module IW(	// src/main/scala/stages/IW.scala:26:7
  input         clock,	// src/main/scala/stages/IW.scala:26:7
                reset,	// src/main/scala/stages/IW.scala:26:7
  output        io_ws_allowin,	// src/main/scala/stages/IW.scala:27:16
  input         io_ms_to_ws_valid,	// src/main/scala/stages/IW.scala:27:16
  input  [69:0] io_ms_to_ws_bus,	// src/main/scala/stages/IW.scala:27:16
  output [31:0] io_debug_wb_pc,	// src/main/scala/stages/IW.scala:27:16
  output [3:0]  io_debug_wb_rf_we,	// src/main/scala/stages/IW.scala:27:16
  output [4:0]  io_debug_wb_rf_wnum,	// src/main/scala/stages/IW.scala:27:16
  output [31:0] io_debug_wb_rf_wdata,	// src/main/scala/stages/IW.scala:27:16
  output [37:0] io_ws_to_rf_bus	// src/main/scala/stages/IW.scala:27:16
);

  reg  [69:0] ms_to_ws_bus_r;	// src/main/scala/stages/IW.scala:30:33
  reg         ws_valid;	// src/main/scala/stages/IW.scala:31:27
  wire        rf_we = ms_to_ws_bus_r[69] & ws_valid;	// src/main/scala/stages/IW.scala:30:33, :31:27, :41:41, :47:26
  always @(posedge clock) begin	// src/main/scala/stages/IW.scala:26:7
    if (reset) begin	// src/main/scala/stages/IW.scala:26:7
      ms_to_ws_bus_r <= 70'h0;	// src/main/scala/stages/IW.scala:30:33
      ws_valid <= 1'h0;	// src/main/scala/stages/IW.scala:31:27
    end
    else begin	// src/main/scala/stages/IW.scala:26:7
      if (io_ms_to_ws_valid)	// src/main/scala/stages/IW.scala:27:16
        ms_to_ws_bus_r <= io_ms_to_ws_bus;	// src/main/scala/stages/IW.scala:30:33
      ws_valid <= io_ms_to_ws_valid;	// src/main/scala/stages/IW.scala:31:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/stages/IW.scala:26:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/IW.scala:26:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/IW.scala:26:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/stages/IW.scala:26:7
      automatic logic [31:0] _RANDOM[0:2];	// src/main/scala/stages/IW.scala:26:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/stages/IW.scala:26:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/stages/IW.scala:26:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/stages/IW.scala:26:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/stages/IW.scala:26:7
        end	// src/main/scala/stages/IW.scala:26:7
        ms_to_ws_bus_r = {_RANDOM[2'h0], _RANDOM[2'h1], _RANDOM[2'h2][5:0]};	// src/main/scala/stages/IW.scala:26:7, :30:33
        ws_valid = _RANDOM[2'h2][6];	// src/main/scala/stages/IW.scala:26:7, :30:33, :31:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/stages/IW.scala:26:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/stages/IW.scala:26:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_ws_allowin = 1'h1;	// src/main/scala/stages/IW.scala:26:7, :33:32
  assign io_debug_wb_pc = ms_to_ws_bus_r[31:0];	// src/main/scala/stages/IW.scala:26:7, :30:33, :44:41
  assign io_debug_wb_rf_we = {4{rf_we}};	// src/main/scala/stages/IW.scala:26:7, :47:26, :53:30
  assign io_debug_wb_rf_wnum = ms_to_ws_bus_r[68:64];	// src/main/scala/stages/IW.scala:26:7, :30:33, :42:41
  assign io_debug_wb_rf_wdata = ms_to_ws_bus_r[63:32];	// src/main/scala/stages/IW.scala:26:7, :30:33, :43:41
  assign io_ws_to_rf_bus = {rf_we, ms_to_ws_bus_r[68:32]};	// src/main/scala/stages/IW.scala:26:7, :30:33, :47:26, :50:27
endmodule

