// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module IF(	// src/main/scala/stages/IF/IF.scala:26:7
  input         clock,	// src/main/scala/stages/IF/IF.scala:26:7
                reset,	// src/main/scala/stages/IF/IF.scala:26:7
                io_from_valid,	// src/main/scala/stages/IF/IF.scala:27:16
  output        io_to_valid,	// src/main/scala/stages/IF/IF.scala:27:16
  output [31:0] io_to_bits_pc,	// src/main/scala/stages/IF/IF.scala:27:16
                io_to_bits_inst,	// src/main/scala/stages/IF/IF.scala:27:16
  input  [31:0] io_inst_sram_rdata,	// src/main/scala/stages/IF/IF.scala:27:16
  input         io_br_bus_br_taken,	// src/main/scala/stages/IF/IF.scala:27:16
  input  [31:0] io_br_bus_br_target,	// src/main/scala/stages/IF/IF.scala:27:16
  output        io_inst_sram_en,	// src/main/scala/stages/IF/IF.scala:27:16
  output [31:0] io_inst_sram_addr	// src/main/scala/stages/IF/IF.scala:27:16
);

  reg         info_valid;	// src/main/scala/config/Configs.scala:50:28
  reg  [31:0] fs_pc;	// src/main/scala/stages/IF/IF.scala:33:24
  wire [31:0] _next_pc_T = fs_pc + 32'h4;	// src/main/scala/stages/IF/IF.scala:33:24, :34:70
  always @(posedge clock) begin	// src/main/scala/stages/IF/IF.scala:26:7
    if (reset) begin	// src/main/scala/stages/IF/IF.scala:26:7
      info_valid <= 1'h0;	// src/main/scala/config/Configs.scala:49:40, :50:28
      fs_pc <= 32'h1BFFFFFC;	// src/main/scala/stages/IF/IF.scala:33:24
    end
    else begin	// src/main/scala/stages/IF/IF.scala:26:7
      info_valid <= io_from_valid;	// src/main/scala/config/Configs.scala:50:28
      if (io_from_valid) begin	// src/main/scala/stages/IF/IF.scala:27:16
        if (io_br_bus_br_taken)	// src/main/scala/stages/IF/IF.scala:27:16
          fs_pc <= io_br_bus_br_target;	// src/main/scala/stages/IF/IF.scala:33:24
        else	// src/main/scala/stages/IF/IF.scala:27:16
          fs_pc <= _next_pc_T;	// src/main/scala/stages/IF/IF.scala:33:24, :34:70
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/stages/IF/IF.scala:26:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/IF/IF.scala:26:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/IF/IF.scala:26:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/stages/IF/IF.scala:26:7
      automatic logic [31:0] _RANDOM[0:7];	// src/main/scala/stages/IF/IF.scala:26:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/stages/IF/IF.scala:26:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/stages/IF/IF.scala:26:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/stages/IF/IF.scala:26:7
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;	// src/main/scala/stages/IF/IF.scala:26:7
        end	// src/main/scala/stages/IF/IF.scala:26:7
        info_valid = _RANDOM[3'h6][18];	// src/main/scala/config/Configs.scala:50:28, src/main/scala/stages/IF/IF.scala:26:7
        fs_pc = {_RANDOM[3'h6][31:19], _RANDOM[3'h7][18:0]};	// src/main/scala/config/Configs.scala:50:28, src/main/scala/stages/IF/IF.scala:26:7, :33:24
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/stages/IF/IF.scala:26:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/stages/IF/IF.scala:26:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_to_valid = info_valid;	// src/main/scala/config/Configs.scala:50:28, src/main/scala/stages/IF/IF.scala:26:7
  assign io_to_bits_pc = fs_pc;	// src/main/scala/stages/IF/IF.scala:26:7, :33:24
  assign io_to_bits_inst = io_inst_sram_rdata;	// src/main/scala/stages/IF/IF.scala:26:7
  assign io_inst_sram_en = io_from_valid;	// src/main/scala/stages/IF/IF.scala:26:7
  assign io_inst_sram_addr = io_br_bus_br_taken ? io_br_bus_br_target : _next_pc_T;	// src/main/scala/stages/IF/IF.scala:26:7, :34:{22,70}
endmodule

module REG(	// src/main/scala/stages/ID/REG.scala:18:7
  input         clock,	// src/main/scala/stages/ID/REG.scala:18:7
                reset,	// src/main/scala/stages/ID/REG.scala:18:7
  input  [4:0]  io_raddr1,	// src/main/scala/stages/ID/REG.scala:19:16
                io_raddr2,	// src/main/scala/stages/ID/REG.scala:19:16
  output [31:0] io_rdata1,	// src/main/scala/stages/ID/REG.scala:19:16
                io_rdata2,	// src/main/scala/stages/ID/REG.scala:19:16
  input         io_we,	// src/main/scala/stages/ID/REG.scala:19:16
  input  [4:0]  io_waddr,	// src/main/scala/stages/ID/REG.scala:19:16
  input  [31:0] io_wdata	// src/main/scala/stages/ID/REG.scala:19:16
);

  reg  [31:0]       rf_0;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_1;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_2;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_3;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_4;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_5;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_6;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_7;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_8;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_9;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_10;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_11;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_12;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_13;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_14;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_15;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_16;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_17;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_18;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_19;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_20;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_21;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_22;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_23;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_24;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_25;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_26;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_27;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_28;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_29;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_30;	// src/main/scala/stages/ID/REG.scala:21:21
  reg  [31:0]       rf_31;	// src/main/scala/stages/ID/REG.scala:21:21
  wire [31:0][31:0] _GEN =
    {{rf_31},
     {rf_30},
     {rf_29},
     {rf_28},
     {rf_27},
     {rf_26},
     {rf_25},
     {rf_24},
     {rf_23},
     {rf_22},
     {rf_21},
     {rf_20},
     {rf_19},
     {rf_18},
     {rf_17},
     {rf_16},
     {rf_15},
     {rf_14},
     {rf_13},
     {rf_12},
     {rf_11},
     {rf_10},
     {rf_9},
     {rf_8},
     {rf_7},
     {rf_6},
     {rf_5},
     {rf_4},
     {rf_3},
     {rf_2},
     {rf_1},
     {rf_0}};	// src/main/scala/stages/ID/REG.scala:21:21, :27:21
  always @(posedge clock) begin	// src/main/scala/stages/ID/REG.scala:18:7
    if (reset) begin	// src/main/scala/stages/ID/REG.scala:18:7
      rf_0 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_1 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_2 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_3 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_4 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_5 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_6 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_7 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_8 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_9 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_10 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_11 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_12 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_13 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_14 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_15 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_16 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_17 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_18 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_19 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_20 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_21 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_22 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_23 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_24 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_25 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_26 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_27 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_28 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_29 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_30 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
      rf_31 <= 32'h0;	// src/main/scala/stages/ID/REG.scala:21:{21,29}
    end
    else begin	// src/main/scala/stages/ID/REG.scala:18:7
      automatic logic _GEN_0 = io_we & (|io_waddr);	// src/main/scala/stages/ID/REG.scala:23:{16,28}
      if (_GEN_0 & ~(|io_waddr))	// src/main/scala/stages/ID/REG.scala:21:21, :23:{16,28,37}, :24:22
        rf_0 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h1)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_1 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h2)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_2 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h3)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_3 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h4)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_4 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h5)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_5 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h6)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_6 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h7)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_7 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h8)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_8 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h9)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_9 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'hA)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_10 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'hB)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_11 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'hC)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_12 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'hD)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_13 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'hE)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_14 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'hF)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_15 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h10)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_16 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h11)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_17 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h12)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_18 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h13)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_19 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h14)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_20 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h15)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_21 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h16)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_22 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h17)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_23 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h18)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_24 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h19)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_25 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h1A)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_26 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h1B)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_27 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h1C)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_28 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h1D)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_29 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & io_waddr == 5'h1E)	// src/main/scala/stages/ID/REG.scala:18:7, :21:21, :23:{16,37}, :24:22
        rf_30 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
      if (_GEN_0 & (&io_waddr))	// src/main/scala/stages/ID/REG.scala:21:21, :23:{16,37}, :24:22
        rf_31 <= io_wdata;	// src/main/scala/stages/ID/REG.scala:21:21
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/stages/ID/REG.scala:18:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/ID/REG.scala:18:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/ID/REG.scala:18:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/stages/ID/REG.scala:18:7
      automatic logic [31:0] _RANDOM[0:31];	// src/main/scala/stages/ID/REG.scala:18:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/stages/ID/REG.scala:18:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/stages/ID/REG.scala:18:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/stages/ID/REG.scala:18:7
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          _RANDOM[i[4:0]] = `RANDOM;	// src/main/scala/stages/ID/REG.scala:18:7
        end	// src/main/scala/stages/ID/REG.scala:18:7
        rf_0 = _RANDOM[5'h0];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_1 = _RANDOM[5'h1];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_2 = _RANDOM[5'h2];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_3 = _RANDOM[5'h3];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_4 = _RANDOM[5'h4];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_5 = _RANDOM[5'h5];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_6 = _RANDOM[5'h6];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_7 = _RANDOM[5'h7];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_8 = _RANDOM[5'h8];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_9 = _RANDOM[5'h9];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_10 = _RANDOM[5'hA];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_11 = _RANDOM[5'hB];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_12 = _RANDOM[5'hC];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_13 = _RANDOM[5'hD];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_14 = _RANDOM[5'hE];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_15 = _RANDOM[5'hF];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_16 = _RANDOM[5'h10];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_17 = _RANDOM[5'h11];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_18 = _RANDOM[5'h12];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_19 = _RANDOM[5'h13];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_20 = _RANDOM[5'h14];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_21 = _RANDOM[5'h15];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_22 = _RANDOM[5'h16];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_23 = _RANDOM[5'h17];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_24 = _RANDOM[5'h18];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_25 = _RANDOM[5'h19];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_26 = _RANDOM[5'h1A];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_27 = _RANDOM[5'h1B];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_28 = _RANDOM[5'h1C];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_29 = _RANDOM[5'h1D];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_30 = _RANDOM[5'h1E];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
        rf_31 = _RANDOM[5'h1F];	// src/main/scala/stages/ID/REG.scala:18:7, :21:21
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/stages/ID/REG.scala:18:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/stages/ID/REG.scala:18:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rdata1 = io_raddr1 == 5'h0 ? 32'h0 : _GEN[io_raddr1];	// src/main/scala/stages/ID/REG.scala:18:7, :21:29, :27:{21,32}
  assign io_rdata2 = io_raddr2 == 5'h0 ? 32'h0 : _GEN[io_raddr2];	// src/main/scala/stages/ID/REG.scala:18:7, :21:29, :27:21, :28:{21,32}
endmodule

module ID(	// src/main/scala/stages/ID/ID.scala:134:7
  input         clock,	// src/main/scala/stages/ID/ID.scala:134:7
                reset,	// src/main/scala/stages/ID/ID.scala:134:7
                io_from_valid,	// src/main/scala/stages/ID/ID.scala:135:16
  input  [31:0] io_from_bits_pc,	// src/main/scala/stages/ID/ID.scala:135:16
                io_from_bits_inst,	// src/main/scala/stages/ID/ID.scala:135:16
  output        io_to_valid,	// src/main/scala/stages/ID/ID.scala:135:16
  output [31:0] io_to_bits_pc,	// src/main/scala/stages/ID/ID.scala:135:16
  output [5:0]  io_to_bits_alu_op,	// src/main/scala/stages/ID/ID.scala:135:16
  output        io_to_bits_src1_is_pc,	// src/main/scala/stages/ID/ID.scala:135:16
                io_to_bits_src2_is_imm,	// src/main/scala/stages/ID/ID.scala:135:16
                io_to_bits_src2_is_4,	// src/main/scala/stages/ID/ID.scala:135:16
                io_to_bits_gr_we,	// src/main/scala/stages/ID/ID.scala:135:16
                io_to_bits_mem_we,	// src/main/scala/stages/ID/ID.scala:135:16
  output [4:0]  io_to_bits_dest,	// src/main/scala/stages/ID/ID.scala:135:16
  output [31:0] io_to_bits_imm,	// src/main/scala/stages/ID/ID.scala:135:16
                io_to_bits_rj_value,	// src/main/scala/stages/ID/ID.scala:135:16
                io_to_bits_rkd_value,	// src/main/scala/stages/ID/ID.scala:135:16
  output        io_to_bits_res_from_mem,	// src/main/scala/stages/ID/ID.scala:135:16
  input  [37:0] io_ws_to_rf_bus,	// src/main/scala/stages/ID/ID.scala:135:16
  output        io_br_bus_br_taken,	// src/main/scala/stages/ID/ID.scala:135:16
  output [31:0] io_br_bus_br_target	// src/main/scala/stages/ID/ID.scala:135:16
);

  wire [31:0] _u_regfile_io_rdata1;	// src/main/scala/stages/ID/ID.scala:191:27
  wire [31:0] _u_regfile_io_rdata2;	// src/main/scala/stages/ID/ID.scala:191:27
  reg  [31:0] info_pc;	// src/main/scala/config/Configs.scala:49:27
  reg  [31:0] info_inst;	// src/main/scala/config/Configs.scala:49:27
  reg         info_valid;	// src/main/scala/config/Configs.scala:50:28
  wire        _GEN = info_inst[31:15] == 17'h20;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_0 = info_inst[31:15] == 17'h22;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_1 = info_inst[31:15] == 17'h24;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_2 = info_inst[31:15] == 17'h25;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_3 = info_inst[31:15] == 17'h28;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_4 = info_inst[31:15] == 17'h29;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_5 = info_inst[31:15] == 17'h2A;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_6 = info_inst[31:22] == 10'hE;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_7 = info_inst[31:15] == 17'h2B;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_8 = info_inst[31:15] == 17'h81;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_9 = info_inst[31:15] == 17'h89;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_10 = info_inst[31:15] == 17'h91;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_11 = info_inst[31:22] == 10'hA;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_12 = info_inst[31:22] == 10'hA2;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_13 = info_inst[31:22] == 10'hA6;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_14 = info_inst[31:26] == 6'h13;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_15 = info_inst[31:26] == 6'h14;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_16 = info_inst[31:26] == 6'h15;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_17 = info_inst[31:26] == 6'h16;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_18 = info_inst[31:26] == 6'h17;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_19 = info_inst[31:25] == 7'hA;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_20 = {info_inst[31:24], info_inst[9:5]} == 13'h81;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27
  wire        _GEN_21 = _GEN_17 | _GEN_18;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire        _GEN_22 = _GEN_15 | _GEN_16;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire        _GEN_23 = _GEN_11 | _GEN_12 | _GEN_13;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire        _GEN_24 = _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [4:0]  instType =
    _GEN_24
      ? 5'h3
      : _GEN_6
          ? 5'h1
          : _GEN_7
              ? 5'h3
              : _GEN_8 | _GEN_9 | _GEN_10
                  ? 5'h9
                  : _GEN_23
                      ? 5'h1
                      : _GEN_14
                          ? 5'h6
                          : _GEN_22
                              ? 5'h8
                              : _GEN_21 ? 5'h6 : _GEN_19 ? 5'h7 : _GEN_20 ? 5'h11 : 5'hF;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire        _GEN_25 = _GEN_8 | _GEN_9 | _GEN_10 | _GEN_23;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [1:0]  src2Type =
    _GEN_24
      ? 2'h0
      : _GEN_6
          ? 2'h1
          : _GEN_7
              ? 2'h0
              : _GEN_25
                  ? 2'h1
                  : _GEN_14
                      ? 2'h2
                      : _GEN_15
                          ? 2'h0
                          : _GEN_16 ? 2'h2 : {1'h0, ~_GEN_21 & (_GEN_19 | _GEN_20)};	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/config/Configs.scala:49:40, src/main/scala/stages/ID/ID.scala:164:73
  wire        src2_is_4 = src2Type == 2'h2;	// src/main/scala/chisel3/util/Lookup.scala:34:39, src/main/scala/stages/ID/ID.scala:170:30
  wire        rj_eq_rd = _u_regfile_io_rdata1 == _u_regfile_io_rdata2;	// src/main/scala/stages/ID/ID.scala:191:27, :202:30
  always @(posedge clock) begin	// src/main/scala/stages/ID/ID.scala:134:7
    if (reset) begin	// src/main/scala/stages/ID/ID.scala:134:7
      info_pc <= 32'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_inst <= 32'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_valid <= 1'h0;	// src/main/scala/config/Configs.scala:49:40, :50:28
    end
    else begin	// src/main/scala/stages/ID/ID.scala:134:7
      if (io_from_valid) begin	// src/main/scala/stages/ID/ID.scala:135:16
        info_pc <= io_from_bits_pc;	// src/main/scala/config/Configs.scala:49:27
        info_inst <= io_from_bits_inst;	// src/main/scala/config/Configs.scala:49:27
      end
      info_valid <= io_from_valid;	// src/main/scala/config/Configs.scala:50:28
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/stages/ID/ID.scala:134:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/ID/ID.scala:134:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/ID/ID.scala:134:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/stages/ID/ID.scala:134:7
      automatic logic [31:0] _RANDOM[0:6];	// src/main/scala/stages/ID/ID.scala:134:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/stages/ID/ID.scala:134:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/stages/ID/ID.scala:134:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/stages/ID/ID.scala:134:7
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/stages/ID/ID.scala:134:7
        end	// src/main/scala/stages/ID/ID.scala:134:7
        info_pc = _RANDOM[3'h0];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/ID/ID.scala:134:7
        info_inst = _RANDOM[3'h1];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/ID/ID.scala:134:7
        info_valid = _RANDOM[3'h6][18];	// src/main/scala/config/Configs.scala:50:28, src/main/scala/stages/ID/ID.scala:134:7
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/stages/ID/ID.scala:134:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/stages/ID/ID.scala:134:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  REG u_regfile (	// src/main/scala/stages/ID/ID.scala:191:27
    .clock     (clock),
    .reset     (reset),
    .io_raddr1 (info_inst[9:5]),	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/ID/ID.scala:146:23
    .io_raddr2
      (~(_GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7
         | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_11 | _GEN_12)
       & (_GEN_13 | ~(_GEN_14 | _GEN_22) & (_GEN_17 | _GEN_18))
         ? info_inst[4:0]
         : info_inst[14:10]),	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/ID/ID.scala:145:23, :147:23, :183:24
    .io_rdata1 (_u_regfile_io_rdata1),
    .io_rdata2 (_u_regfile_io_rdata2),
    .io_we     (io_ws_to_rf_bus[37]),	// src/main/scala/stages/ID/ID.scala:186:32
    .io_waddr  (io_ws_to_rf_bus[36:32]),	// src/main/scala/stages/ID/ID.scala:187:35
    .io_wdata  (io_ws_to_rf_bus[31:0])	// src/main/scala/stages/ID/ID.scala:188:35
  );
  assign io_to_valid = info_valid;	// src/main/scala/config/Configs.scala:50:28, src/main/scala/stages/ID/ID.scala:134:7
  assign io_to_bits_pc = info_pc;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/ID/ID.scala:134:7
  assign io_to_bits_alu_op =
    _GEN
      ? 6'h20
      : _GEN_0
          ? 6'h21
          : _GEN_1
              ? 6'h22
              : _GEN_2
                  ? 6'h23
                  : _GEN_3
                      ? 6'h25
                      : _GEN_4
                          ? 6'h24
                          : _GEN_5 | _GEN_6
                              ? 6'h26
                              : _GEN_7
                                  ? 6'h27
                                  : _GEN_8
                                      ? 6'h28
                                      : _GEN_9
                                          ? 6'h29
                                          : _GEN_10
                                              ? 6'h2A
                                              : _GEN_11 | _GEN_12 | _GEN_13 | _GEN_14
                                                  ? 6'h20
                                                  : _GEN_15
                                                      ? 6'h0
                                                      : _GEN_16
                                                          ? 6'h20
                                                          : _GEN_21
                                                              ? 6'h0
                                                              : _GEN_19
                                                                  ? 6'h2B
                                                                  : _GEN_20
                                                                      ? 6'h1
                                                                      : 6'h20;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/config/Configs.scala:49:40, src/main/scala/stages/ID/ID.scala:134:7
  assign io_to_bits_src1_is_pc =
    ~(_GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6 | _GEN_7
      | _GEN_25) & (_GEN_14 | ~_GEN_15 & _GEN_16);	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/stages/ID/ID.scala:134:7
  assign io_to_bits_src2_is_imm = src2_is_4 | src2Type == 2'h1;	// src/main/scala/chisel3/util/Lookup.scala:34:39, src/main/scala/stages/ID/ID.scala:134:7, :170:30, :171:{33,45}
  assign io_to_bits_src2_is_4 = src2_is_4;	// src/main/scala/stages/ID/ID.scala:134:7, :170:30
  assign io_to_bits_gr_we =
    info_inst[31:22] != 10'hA6 & info_inst[31:26] != 6'h16 & info_inst[31:26] != 6'h17
    & info_inst[31:26] != 6'h14;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/ID/ID.scala:134:7, :175:33, :176:33, :177:{33,54}, :178:33
  assign io_to_bits_mem_we = info_inst[31:22] == 10'hA6;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/ID/ID.scala:134:7, :179:33
  assign io_to_bits_dest = info_inst[31:26] == 6'h15 ? 5'h1 : info_inst[4:0];	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/ID/ID.scala:134:7, :145:23, :174:33, :180:27
  assign io_to_bits_imm =
    instType == 5'h9
      ? {27'h0, info_inst[14:10]}
      : instType == 5'h7
          ? {info_inst[24:5], 12'h0}
          : instType == 5'h1 ? {{20{info_inst[21]}}, info_inst[21:10]} : 32'h4;	// src/main/scala/chisel3/util/Lookup.scala:34:39, src/main/scala/config/Configs.scala:32:{28,43}, :33:16, :49:27, :93:32, src/main/scala/stages/ID/ID.scala:134:7, :147:23, :148:23, :149:23, :159:{25,35}
  assign io_to_bits_rj_value = _u_regfile_io_rdata1;	// src/main/scala/stages/ID/ID.scala:134:7, :191:27
  assign io_to_bits_rkd_value = _u_regfile_io_rdata2;	// src/main/scala/stages/ID/ID.scala:134:7, :191:27
  assign io_to_bits_res_from_mem = info_inst[31:22] == 10'hA2;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/ID/ID.scala:134:7, :173:33
  assign io_br_bus_br_taken =
    (info_inst[31:26] == 6'h16 & rj_eq_rd | info_inst[31:26] == 6'h17 & ~rj_eq_rd
     | info_inst[31:26] == 6'h13 | info_inst[31:26] == 6'h15 | info_inst[31:26] == 6'h14)
    & info_valid;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/config/Configs.scala:49:27, :50:28, src/main/scala/stages/ID/ID.scala:134:7, :202:30, :203:{29,50}, :204:{29,50,53}, :205:29, :206:29, :207:{18,29,49}
  assign io_br_bus_br_target =
    info_inst[31:26] == 6'h16 | info_inst[31:26] == 6'h17 | info_inst[31:26] == 6'h14
    | info_inst[31:26] == 6'h15
      ? info_pc
        + {instType == 5'h8 ? {{4{info_inst[9]}}, info_inst[9:0]} : {14{info_inst[25]}},
           info_inst[25:10],
           2'h0}
      : _u_regfile_io_rdata1 + {{14{info_inst[25]}}, info_inst[25:10], 2'h0};	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/config/Configs.scala:32:{28,43}, :33:16, :49:27, src/main/scala/stages/ID/ID.scala:134:7, :150:23, :151:27, :164:{22,32,73}, :191:27, :209:{24,34}, :210:34, :211:34, :212:{23,34}, :213:32, :214:35
endmodule

module ALU(	// src/main/scala/stages/EXE/ALU.scala:31:7
  input  [5:0]  io_alu_op,	// src/main/scala/stages/EXE/ALU.scala:32:16
  input  [31:0] io_alu_src1,	// src/main/scala/stages/EXE/ALU.scala:32:16
                io_alu_src2,	// src/main/scala/stages/EXE/ALU.scala:32:16
  output [31:0] io_alu_result	// src/main/scala/stages/EXE/ALU.scala:32:16
);

  wire [31:0] _io_alu_result_T_13 = io_alu_src1 | io_alu_src2;	// src/main/scala/stages/EXE/ALU.scala:40:45
  wire [62:0] _io_alu_result_T_16 = {31'h0, io_alu_src1} << io_alu_src2[4:0];	// src/main/scala/stages/EXE/ALU.scala:43:{43,58}
  wire [63:0] _io_alu_result_T_23 =
    {{32{io_alu_src1[31]}}, io_alu_src1} >> io_alu_src2[4:0];	// src/main/scala/stages/EXE/ALU.scala:43:58, :45:{34,39,55,75}
  assign io_alu_result =
    io_alu_op == 6'h2B
      ? io_alu_src2
      : io_alu_op == 6'h2A
          ? _io_alu_result_T_23[31:0]
          : io_alu_op == 6'h29
              ? io_alu_src1 >> io_alu_src2[4:0]
              : io_alu_op == 6'h28
                  ? _io_alu_result_T_16[31:0]
                  : io_alu_op == 6'h27
                      ? io_alu_src1 ^ io_alu_src2
                      : io_alu_op == 6'h26
                          ? _io_alu_result_T_13
                          : io_alu_op == 6'h25
                              ? ~_io_alu_result_T_13
                              : io_alu_op == 6'h24
                                  ? io_alu_src1 & io_alu_src2
                                  : io_alu_op == 6'h23
                                      ? {31'h0, io_alu_src1 < io_alu_src2}
                                      : io_alu_op == 6'h22
                                          ? {31'h0,
                                             $signed(io_alu_src1) < $signed(io_alu_src2)}
                                          : io_alu_op == 6'h21
                                              ? io_alu_src1 - io_alu_src2
                                              : io_alu_op == 6'h20
                                                  ? io_alu_src1 + io_alu_src2
                                                  : 32'h0;	// src/main/scala/config/Configs.scala:93:32, src/main/scala/stages/EXE/ALU.scala:31:7, :35:56, :36:56, :37:54, :38:47, :39:43, :40:{31,45}, :42:43, :43:{43,58}, :44:43, :45:{39,75,98}
endmodule

module IE(	// src/main/scala/stages/EXE/IE.scala:20:7
  input         clock,	// src/main/scala/stages/EXE/IE.scala:20:7
                reset,	// src/main/scala/stages/EXE/IE.scala:20:7
                io_from_valid,	// src/main/scala/stages/EXE/IE.scala:21:16
  input  [31:0] io_from_bits_pc,	// src/main/scala/stages/EXE/IE.scala:21:16
  input  [5:0]  io_from_bits_alu_op,	// src/main/scala/stages/EXE/IE.scala:21:16
  input         io_from_bits_src1_is_pc,	// src/main/scala/stages/EXE/IE.scala:21:16
                io_from_bits_src2_is_imm,	// src/main/scala/stages/EXE/IE.scala:21:16
                io_from_bits_src2_is_4,	// src/main/scala/stages/EXE/IE.scala:21:16
                io_from_bits_gr_we,	// src/main/scala/stages/EXE/IE.scala:21:16
                io_from_bits_mem_we,	// src/main/scala/stages/EXE/IE.scala:21:16
  input  [4:0]  io_from_bits_dest,	// src/main/scala/stages/EXE/IE.scala:21:16
  input  [31:0] io_from_bits_imm,	// src/main/scala/stages/EXE/IE.scala:21:16
                io_from_bits_rj_value,	// src/main/scala/stages/EXE/IE.scala:21:16
                io_from_bits_rkd_value,	// src/main/scala/stages/EXE/IE.scala:21:16
  input         io_from_bits_res_from_mem,	// src/main/scala/stages/EXE/IE.scala:21:16
  output        io_to_valid,	// src/main/scala/stages/EXE/IE.scala:21:16
  output [31:0] io_to_bits_pc,	// src/main/scala/stages/EXE/IE.scala:21:16
  output        io_to_bits_gr_we,	// src/main/scala/stages/EXE/IE.scala:21:16
                io_to_bits_mem_we,	// src/main/scala/stages/EXE/IE.scala:21:16
  output [4:0]  io_to_bits_dest,	// src/main/scala/stages/EXE/IE.scala:21:16
  output [31:0] io_to_bits_rkd_value,	// src/main/scala/stages/EXE/IE.scala:21:16
  output        io_to_bits_res_from_mem,	// src/main/scala/stages/EXE/IE.scala:21:16
  output [31:0] io_to_bits_alu_result	// src/main/scala/stages/EXE/IE.scala:21:16
);

  reg [31:0] info_pc;	// src/main/scala/config/Configs.scala:49:27
  reg [5:0]  info_alu_op;	// src/main/scala/config/Configs.scala:49:27
  reg        src1_is_pc;	// src/main/scala/config/Configs.scala:49:27
  reg        src2_is_imm;	// src/main/scala/config/Configs.scala:49:27
  reg        src2_is_4;	// src/main/scala/config/Configs.scala:49:27
  reg        info_gr_we;	// src/main/scala/config/Configs.scala:49:27
  reg        es_mem_we;	// src/main/scala/config/Configs.scala:49:27
  reg [4:0]  info_dest;	// src/main/scala/config/Configs.scala:49:27
  reg [31:0] info_imm;	// src/main/scala/config/Configs.scala:49:27
  reg [31:0] info_rj_value;	// src/main/scala/config/Configs.scala:49:27
  reg [31:0] info_rkd_value;	// src/main/scala/config/Configs.scala:49:27
  reg        info_res_from_mem;	// src/main/scala/config/Configs.scala:49:27
  reg        info_valid;	// src/main/scala/config/Configs.scala:50:28
  always @(posedge clock) begin	// src/main/scala/stages/EXE/IE.scala:20:7
    if (reset) begin	// src/main/scala/stages/EXE/IE.scala:20:7
      info_pc <= 32'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_alu_op <= 6'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      src1_is_pc <= 1'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      src2_is_imm <= 1'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      src2_is_4 <= 1'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_gr_we <= 1'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      es_mem_we <= 1'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_dest <= 5'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_imm <= 32'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_rj_value <= 32'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_rkd_value <= 32'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_res_from_mem <= 1'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_valid <= 1'h0;	// src/main/scala/config/Configs.scala:49:40, :50:28
    end
    else begin	// src/main/scala/stages/EXE/IE.scala:20:7
      if (io_from_valid) begin	// src/main/scala/stages/EXE/IE.scala:21:16
        info_pc <= io_from_bits_pc;	// src/main/scala/config/Configs.scala:49:27
        info_alu_op <= io_from_bits_alu_op;	// src/main/scala/config/Configs.scala:49:27
        src1_is_pc <= io_from_bits_src1_is_pc;	// src/main/scala/config/Configs.scala:49:27
        src2_is_imm <= io_from_bits_src2_is_imm;	// src/main/scala/config/Configs.scala:49:27
        src2_is_4 <= io_from_bits_src2_is_4;	// src/main/scala/config/Configs.scala:49:27
        info_gr_we <= io_from_bits_gr_we;	// src/main/scala/config/Configs.scala:49:27
        es_mem_we <= io_from_bits_mem_we;	// src/main/scala/config/Configs.scala:49:27
        info_dest <= io_from_bits_dest;	// src/main/scala/config/Configs.scala:49:27
        info_imm <= io_from_bits_imm;	// src/main/scala/config/Configs.scala:49:27
        info_rj_value <= io_from_bits_rj_value;	// src/main/scala/config/Configs.scala:49:27
        info_rkd_value <= io_from_bits_rkd_value;	// src/main/scala/config/Configs.scala:49:27
        info_res_from_mem <= io_from_bits_res_from_mem;	// src/main/scala/config/Configs.scala:49:27
      end
      info_valid <= io_from_valid;	// src/main/scala/config/Configs.scala:50:28
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/stages/EXE/IE.scala:20:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/EXE/IE.scala:20:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/EXE/IE.scala:20:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/stages/EXE/IE.scala:20:7
      automatic logic [31:0] _RANDOM[0:6];	// src/main/scala/stages/EXE/IE.scala:20:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/stages/EXE/IE.scala:20:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/stages/EXE/IE.scala:20:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/stages/EXE/IE.scala:20:7
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/stages/EXE/IE.scala:20:7
        end	// src/main/scala/stages/EXE/IE.scala:20:7
        info_pc = _RANDOM[3'h0];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
        info_alu_op = _RANDOM[3'h2][5:0];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
        src1_is_pc = _RANDOM[3'h2][7];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
        src2_is_imm = _RANDOM[3'h2][8];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
        src2_is_4 = _RANDOM[3'h2][9];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
        info_gr_we = _RANDOM[3'h2][10];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
        es_mem_we = _RANDOM[3'h2][11];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
        info_dest = _RANDOM[3'h2][16:12];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
        info_imm = {_RANDOM[3'h2][31:17], _RANDOM[3'h3][16:0]};	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
        info_rj_value = {_RANDOM[3'h3][31:17], _RANDOM[3'h4][16:0]};	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
        info_rkd_value = {_RANDOM[3'h4][31:17], _RANDOM[3'h5][16:0]};	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
        info_res_from_mem = _RANDOM[3'h5][17];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
        info_valid = _RANDOM[3'h6][18];	// src/main/scala/config/Configs.scala:50:28, src/main/scala/stages/EXE/IE.scala:20:7
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/stages/EXE/IE.scala:20:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/stages/EXE/IE.scala:20:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ALU alu (	// src/main/scala/stages/EXE/IE.scala:44:21
    .io_alu_op     (info_alu_op),	// src/main/scala/config/Configs.scala:49:27
    .io_alu_src1   (src1_is_pc ? info_pc : info_rj_value),	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:46:27
    .io_alu_src2   (src2_is_imm ? info_imm : src2_is_4 ? 32'h4 : info_rkd_value),	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:47:{27,49}
    .io_alu_result (io_to_bits_alu_result)
  );
  assign io_to_valid = info_valid;	// src/main/scala/config/Configs.scala:50:28, src/main/scala/stages/EXE/IE.scala:20:7
  assign io_to_bits_pc = info_pc;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
  assign io_to_bits_gr_we = info_gr_we;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
  assign io_to_bits_mem_we = es_mem_we;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
  assign io_to_bits_dest = info_dest;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
  assign io_to_bits_rkd_value = info_rkd_value;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
  assign io_to_bits_res_from_mem = info_res_from_mem;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/EXE/IE.scala:20:7
endmodule

module IM(	// src/main/scala/stages/MEM/IM.scala:23:7
  input         clock,	// src/main/scala/stages/MEM/IM.scala:23:7
                reset,	// src/main/scala/stages/MEM/IM.scala:23:7
                io_from_valid,	// src/main/scala/stages/MEM/IM.scala:24:16
  input  [31:0] io_from_bits_pc,	// src/main/scala/stages/MEM/IM.scala:24:16
  input         io_from_bits_gr_we,	// src/main/scala/stages/MEM/IM.scala:24:16
                io_from_bits_mem_we,	// src/main/scala/stages/MEM/IM.scala:24:16
  input  [4:0]  io_from_bits_dest,	// src/main/scala/stages/MEM/IM.scala:24:16
  input  [31:0] io_from_bits_rkd_value,	// src/main/scala/stages/MEM/IM.scala:24:16
  input         io_from_bits_res_from_mem,	// src/main/scala/stages/MEM/IM.scala:24:16
  input  [31:0] io_from_bits_alu_result,	// src/main/scala/stages/MEM/IM.scala:24:16
  output        io_to_valid,	// src/main/scala/stages/MEM/IM.scala:24:16
  output [31:0] io_to_bits_pc,	// src/main/scala/stages/MEM/IM.scala:24:16
  output        io_to_bits_gr_we,	// src/main/scala/stages/MEM/IM.scala:24:16
  output [4:0]  io_to_bits_dest,	// src/main/scala/stages/MEM/IM.scala:24:16
  output        io_to_bits_res_from_mem,	// src/main/scala/stages/MEM/IM.scala:24:16
  output [31:0] io_to_bits_alu_result,	// src/main/scala/stages/MEM/IM.scala:24:16
  output [3:0]  io_data_sram_we,	// src/main/scala/stages/MEM/IM.scala:24:16
  output [31:0] io_data_sram_addr,	// src/main/scala/stages/MEM/IM.scala:24:16
                io_data_sram_wdata	// src/main/scala/stages/MEM/IM.scala:24:16
);

  reg [31:0] info_pc;	// src/main/scala/config/Configs.scala:49:27
  reg        ms_gr_we;	// src/main/scala/config/Configs.scala:49:27
  reg        info_mem_we;	// src/main/scala/config/Configs.scala:49:27
  reg [4:0]  info_dest;	// src/main/scala/config/Configs.scala:49:27
  reg [31:0] info_rkd_value;	// src/main/scala/config/Configs.scala:49:27
  reg        ms_res_from_mem;	// src/main/scala/config/Configs.scala:49:27
  reg [31:0] info_alu_result;	// src/main/scala/config/Configs.scala:49:27
  reg        info_valid;	// src/main/scala/config/Configs.scala:50:28
  always @(posedge clock) begin	// src/main/scala/stages/MEM/IM.scala:23:7
    if (reset) begin	// src/main/scala/stages/MEM/IM.scala:23:7
      info_pc <= 32'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      ms_gr_we <= 1'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_mem_we <= 1'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_dest <= 5'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_rkd_value <= 32'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      ms_res_from_mem <= 1'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_alu_result <= 32'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      info_valid <= 1'h0;	// src/main/scala/config/Configs.scala:49:40, :50:28
    end
    else begin	// src/main/scala/stages/MEM/IM.scala:23:7
      if (io_from_valid) begin	// src/main/scala/stages/MEM/IM.scala:24:16
        info_pc <= io_from_bits_pc;	// src/main/scala/config/Configs.scala:49:27
        ms_gr_we <= io_from_bits_gr_we;	// src/main/scala/config/Configs.scala:49:27
        info_mem_we <= io_from_bits_mem_we;	// src/main/scala/config/Configs.scala:49:27
        info_dest <= io_from_bits_dest;	// src/main/scala/config/Configs.scala:49:27
        info_rkd_value <= io_from_bits_rkd_value;	// src/main/scala/config/Configs.scala:49:27
        ms_res_from_mem <= io_from_bits_res_from_mem;	// src/main/scala/config/Configs.scala:49:27
        info_alu_result <= io_from_bits_alu_result;	// src/main/scala/config/Configs.scala:49:27
      end
      info_valid <= io_from_valid;	// src/main/scala/config/Configs.scala:50:28
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/stages/MEM/IM.scala:23:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/MEM/IM.scala:23:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/MEM/IM.scala:23:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/stages/MEM/IM.scala:23:7
      automatic logic [31:0] _RANDOM[0:6];	// src/main/scala/stages/MEM/IM.scala:23:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/stages/MEM/IM.scala:23:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/stages/MEM/IM.scala:23:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/stages/MEM/IM.scala:23:7
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/stages/MEM/IM.scala:23:7
        end	// src/main/scala/stages/MEM/IM.scala:23:7
        info_pc = _RANDOM[3'h0];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
        ms_gr_we = _RANDOM[3'h2][10];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
        info_mem_we = _RANDOM[3'h2][11];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
        info_dest = _RANDOM[3'h2][16:12];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
        info_rkd_value = {_RANDOM[3'h4][31:17], _RANDOM[3'h5][16:0]};	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
        ms_res_from_mem = _RANDOM[3'h5][17];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
        info_alu_result = {_RANDOM[3'h5][31:18], _RANDOM[3'h6][17:0]};	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
        info_valid = _RANDOM[3'h6][18];	// src/main/scala/config/Configs.scala:49:27, :50:28, src/main/scala/stages/MEM/IM.scala:23:7
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/stages/MEM/IM.scala:23:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/stages/MEM/IM.scala:23:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_to_valid = info_valid;	// src/main/scala/config/Configs.scala:50:28, src/main/scala/stages/MEM/IM.scala:23:7
  assign io_to_bits_pc = info_pc;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
  assign io_to_bits_gr_we = ms_gr_we;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
  assign io_to_bits_dest = info_dest;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
  assign io_to_bits_res_from_mem = ms_res_from_mem;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
  assign io_to_bits_alu_result = info_alu_result;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
  assign io_data_sram_we = {4{info_mem_we}};	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7, :48:28
  assign io_data_sram_addr = info_alu_result;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
  assign io_data_sram_wdata = info_rkd_value;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/MEM/IM.scala:23:7
endmodule

module IW(	// src/main/scala/stages/WB/IW.scala:26:7
  input         clock,	// src/main/scala/stages/WB/IW.scala:26:7
                reset,	// src/main/scala/stages/WB/IW.scala:26:7
                io_from_valid,	// src/main/scala/stages/WB/IW.scala:27:16
  input  [31:0] io_from_bits_pc,	// src/main/scala/stages/WB/IW.scala:27:16
  input         io_from_bits_gr_we,	// src/main/scala/stages/WB/IW.scala:27:16
  input  [4:0]  io_from_bits_dest,	// src/main/scala/stages/WB/IW.scala:27:16
  input         io_from_bits_res_from_mem,	// src/main/scala/stages/WB/IW.scala:27:16
  input  [31:0] io_from_bits_alu_result,	// src/main/scala/stages/WB/IW.scala:27:16
  output [31:0] io_debug_wb_pc,	// src/main/scala/stages/WB/IW.scala:27:16
  output [3:0]  io_debug_wb_rf_we,	// src/main/scala/stages/WB/IW.scala:27:16
  output [4:0]  io_debug_wb_rf_wnum,	// src/main/scala/stages/WB/IW.scala:27:16
  output [31:0] io_debug_wb_rf_wdata,	// src/main/scala/stages/WB/IW.scala:27:16
  output [37:0] io_ws_to_rf_bus,	// src/main/scala/stages/WB/IW.scala:27:16
  input  [31:0] io_data_sram_rdata	// src/main/scala/stages/WB/IW.scala:27:16
);

  reg  [31:0] ms_to_ws_bus_r_pc;	// src/main/scala/config/Configs.scala:49:27
  reg         ws_gr_we;	// src/main/scala/config/Configs.scala:49:27
  reg  [4:0]  ms_to_ws_bus_r_dest;	// src/main/scala/config/Configs.scala:49:27
  reg         ms_res_from_mem;	// src/main/scala/config/Configs.scala:49:27
  reg  [31:0] ms_to_ws_bus_r_alu_result;	// src/main/scala/config/Configs.scala:49:27
  reg         ms_to_ws_bus_r_valid;	// src/main/scala/config/Configs.scala:50:28
  wire        rf_we = ws_gr_we & ms_to_ws_bus_r_valid;	// src/main/scala/config/Configs.scala:49:27, :50:28, src/main/scala/stages/WB/IW.scala:39:26
  wire [31:0] rf_wdata = ms_res_from_mem ? io_data_sram_rdata : ms_to_ws_bus_r_alu_result;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/WB/IW.scala:41:23
  always @(posedge clock) begin	// src/main/scala/stages/WB/IW.scala:26:7
    if (reset) begin	// src/main/scala/stages/WB/IW.scala:26:7
      ms_to_ws_bus_r_pc <= 32'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      ws_gr_we <= 1'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      ms_to_ws_bus_r_dest <= 5'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      ms_res_from_mem <= 1'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      ms_to_ws_bus_r_alu_result <= 32'h0;	// src/main/scala/config/Configs.scala:49:{27,40}
      ms_to_ws_bus_r_valid <= 1'h0;	// src/main/scala/config/Configs.scala:49:40, :50:28
    end
    else begin	// src/main/scala/stages/WB/IW.scala:26:7
      if (io_from_valid) begin	// src/main/scala/stages/WB/IW.scala:27:16
        ms_to_ws_bus_r_pc <= io_from_bits_pc;	// src/main/scala/config/Configs.scala:49:27
        ws_gr_we <= io_from_bits_gr_we;	// src/main/scala/config/Configs.scala:49:27
        ms_to_ws_bus_r_dest <= io_from_bits_dest;	// src/main/scala/config/Configs.scala:49:27
        ms_res_from_mem <= io_from_bits_res_from_mem;	// src/main/scala/config/Configs.scala:49:27
        ms_to_ws_bus_r_alu_result <= io_from_bits_alu_result;	// src/main/scala/config/Configs.scala:49:27
      end
      ms_to_ws_bus_r_valid <= io_from_valid;	// src/main/scala/config/Configs.scala:50:28
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// src/main/scala/stages/WB/IW.scala:26:7
    `ifdef FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/WB/IW.scala:26:7
      `FIRRTL_BEFORE_INITIAL	// src/main/scala/stages/WB/IW.scala:26:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// src/main/scala/stages/WB/IW.scala:26:7
      automatic logic [31:0] _RANDOM[0:6];	// src/main/scala/stages/WB/IW.scala:26:7
      `ifdef INIT_RANDOM_PROLOG_	// src/main/scala/stages/WB/IW.scala:26:7
        `INIT_RANDOM_PROLOG_	// src/main/scala/stages/WB/IW.scala:26:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// src/main/scala/stages/WB/IW.scala:26:7
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// src/main/scala/stages/WB/IW.scala:26:7
        end	// src/main/scala/stages/WB/IW.scala:26:7
        ms_to_ws_bus_r_pc = _RANDOM[3'h0];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/WB/IW.scala:26:7
        ws_gr_we = _RANDOM[3'h2][10];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/WB/IW.scala:26:7
        ms_to_ws_bus_r_dest = _RANDOM[3'h2][16:12];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/WB/IW.scala:26:7
        ms_res_from_mem = _RANDOM[3'h5][17];	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/WB/IW.scala:26:7
        ms_to_ws_bus_r_alu_result = {_RANDOM[3'h5][31:18], _RANDOM[3'h6][17:0]};	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/WB/IW.scala:26:7
        ms_to_ws_bus_r_valid = _RANDOM[3'h6][18];	// src/main/scala/config/Configs.scala:49:27, :50:28, src/main/scala/stages/WB/IW.scala:26:7
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// src/main/scala/stages/WB/IW.scala:26:7
      `FIRRTL_AFTER_INITIAL	// src/main/scala/stages/WB/IW.scala:26:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_debug_wb_pc = ms_to_ws_bus_r_pc;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/WB/IW.scala:26:7
  assign io_debug_wb_rf_we = {4{rf_we}};	// src/main/scala/stages/WB/IW.scala:26:7, :39:26, :48:30
  assign io_debug_wb_rf_wnum = ms_to_ws_bus_r_dest;	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/WB/IW.scala:26:7
  assign io_debug_wb_rf_wdata = rf_wdata;	// src/main/scala/stages/WB/IW.scala:26:7, :41:23
  assign io_ws_to_rf_bus = {rf_we, ms_to_ws_bus_r_dest, rf_wdata};	// src/main/scala/config/Configs.scala:49:27, src/main/scala/stages/WB/IW.scala:26:7, :39:26, :41:23, :42:27
endmodule

module Top(	// src/main/scala/stages/Top.scala:30:7
  input         clock,	// src/main/scala/stages/Top.scala:30:7
                reset,	// src/main/scala/stages/Top.scala:30:7
  output        io_inst_sram_en,	// src/main/scala/stages/Top.scala:31:16
  output [3:0]  io_inst_sram_we,	// src/main/scala/stages/Top.scala:31:16
  output [31:0] io_inst_sram_addr,	// src/main/scala/stages/Top.scala:31:16
                io_inst_sram_wdata,	// src/main/scala/stages/Top.scala:31:16
  input  [31:0] io_inst_sram_rdata,	// src/main/scala/stages/Top.scala:31:16
  output        io_data_sram_en,	// src/main/scala/stages/Top.scala:31:16
  output [3:0]  io_data_sram_we,	// src/main/scala/stages/Top.scala:31:16
  output [31:0] io_data_sram_addr,	// src/main/scala/stages/Top.scala:31:16
                io_data_sram_wdata,	// src/main/scala/stages/Top.scala:31:16
  input  [31:0] io_data_sram_rdata,	// src/main/scala/stages/Top.scala:31:16
  output [31:0] io_debug_wb_pc,	// src/main/scala/stages/Top.scala:31:16
  output [3:0]  io_debug_wb_rf_we,	// src/main/scala/stages/Top.scala:31:16
  output [4:0]  io_debug_wb_rf_wnum,	// src/main/scala/stages/Top.scala:31:16
  output [31:0] io_debug_wb_rf_wdata	// src/main/scala/stages/Top.scala:31:16
);

  wire [37:0] _ws_io_ws_to_rf_bus;	// src/main/scala/stages/Top.scala:37:20
  wire        _ms_io_to_valid;	// src/main/scala/stages/Top.scala:36:20
  wire [31:0] _ms_io_to_bits_pc;	// src/main/scala/stages/Top.scala:36:20
  wire        _ms_io_to_bits_gr_we;	// src/main/scala/stages/Top.scala:36:20
  wire [4:0]  _ms_io_to_bits_dest;	// src/main/scala/stages/Top.scala:36:20
  wire        _ms_io_to_bits_res_from_mem;	// src/main/scala/stages/Top.scala:36:20
  wire [31:0] _ms_io_to_bits_alu_result;	// src/main/scala/stages/Top.scala:36:20
  wire        _es_io_to_valid;	// src/main/scala/stages/Top.scala:35:20
  wire [31:0] _es_io_to_bits_pc;	// src/main/scala/stages/Top.scala:35:20
  wire        _es_io_to_bits_gr_we;	// src/main/scala/stages/Top.scala:35:20
  wire        _es_io_to_bits_mem_we;	// src/main/scala/stages/Top.scala:35:20
  wire [4:0]  _es_io_to_bits_dest;	// src/main/scala/stages/Top.scala:35:20
  wire [31:0] _es_io_to_bits_rkd_value;	// src/main/scala/stages/Top.scala:35:20
  wire        _es_io_to_bits_res_from_mem;	// src/main/scala/stages/Top.scala:35:20
  wire [31:0] _es_io_to_bits_alu_result;	// src/main/scala/stages/Top.scala:35:20
  wire        _ds_io_to_valid;	// src/main/scala/stages/Top.scala:34:20
  wire [31:0] _ds_io_to_bits_pc;	// src/main/scala/stages/Top.scala:34:20
  wire [5:0]  _ds_io_to_bits_alu_op;	// src/main/scala/stages/Top.scala:34:20
  wire        _ds_io_to_bits_src1_is_pc;	// src/main/scala/stages/Top.scala:34:20
  wire        _ds_io_to_bits_src2_is_imm;	// src/main/scala/stages/Top.scala:34:20
  wire        _ds_io_to_bits_src2_is_4;	// src/main/scala/stages/Top.scala:34:20
  wire        _ds_io_to_bits_gr_we;	// src/main/scala/stages/Top.scala:34:20
  wire        _ds_io_to_bits_mem_we;	// src/main/scala/stages/Top.scala:34:20
  wire [4:0]  _ds_io_to_bits_dest;	// src/main/scala/stages/Top.scala:34:20
  wire [31:0] _ds_io_to_bits_imm;	// src/main/scala/stages/Top.scala:34:20
  wire [31:0] _ds_io_to_bits_rj_value;	// src/main/scala/stages/Top.scala:34:20
  wire [31:0] _ds_io_to_bits_rkd_value;	// src/main/scala/stages/Top.scala:34:20
  wire        _ds_io_to_bits_res_from_mem;	// src/main/scala/stages/Top.scala:34:20
  wire        _ds_io_br_bus_br_taken;	// src/main/scala/stages/Top.scala:34:20
  wire [31:0] _ds_io_br_bus_br_target;	// src/main/scala/stages/Top.scala:34:20
  wire        _fs_io_to_valid;	// src/main/scala/stages/Top.scala:33:20
  wire [31:0] _fs_io_to_bits_pc;	// src/main/scala/stages/Top.scala:33:20
  wire [31:0] _fs_io_to_bits_inst;	// src/main/scala/stages/Top.scala:33:20
  IF fs (	// src/main/scala/stages/Top.scala:33:20
    .clock               (clock),
    .reset               (reset),
    .io_from_valid       (~reset),	// src/main/scala/stages/Top.scala:39:25
    .io_to_valid         (_fs_io_to_valid),
    .io_to_bits_pc       (_fs_io_to_bits_pc),
    .io_to_bits_inst     (_fs_io_to_bits_inst),
    .io_inst_sram_rdata  (io_inst_sram_rdata),
    .io_br_bus_br_taken  (_ds_io_br_bus_br_taken),	// src/main/scala/stages/Top.scala:34:20
    .io_br_bus_br_target (_ds_io_br_bus_br_target),	// src/main/scala/stages/Top.scala:34:20
    .io_inst_sram_en     (io_inst_sram_en),
    .io_inst_sram_addr   (io_inst_sram_addr)
  );
  ID ds (	// src/main/scala/stages/Top.scala:34:20
    .clock                   (clock),
    .reset                   (reset),
    .io_from_valid           (_fs_io_to_valid),	// src/main/scala/stages/Top.scala:33:20
    .io_from_bits_pc         (_fs_io_to_bits_pc),	// src/main/scala/stages/Top.scala:33:20
    .io_from_bits_inst       (_fs_io_to_bits_inst),	// src/main/scala/stages/Top.scala:33:20
    .io_to_valid             (_ds_io_to_valid),
    .io_to_bits_pc           (_ds_io_to_bits_pc),
    .io_to_bits_alu_op       (_ds_io_to_bits_alu_op),
    .io_to_bits_src1_is_pc   (_ds_io_to_bits_src1_is_pc),
    .io_to_bits_src2_is_imm  (_ds_io_to_bits_src2_is_imm),
    .io_to_bits_src2_is_4    (_ds_io_to_bits_src2_is_4),
    .io_to_bits_gr_we        (_ds_io_to_bits_gr_we),
    .io_to_bits_mem_we       (_ds_io_to_bits_mem_we),
    .io_to_bits_dest         (_ds_io_to_bits_dest),
    .io_to_bits_imm          (_ds_io_to_bits_imm),
    .io_to_bits_rj_value     (_ds_io_to_bits_rj_value),
    .io_to_bits_rkd_value    (_ds_io_to_bits_rkd_value),
    .io_to_bits_res_from_mem (_ds_io_to_bits_res_from_mem),
    .io_ws_to_rf_bus         (_ws_io_ws_to_rf_bus),	// src/main/scala/stages/Top.scala:37:20
    .io_br_bus_br_taken      (_ds_io_br_bus_br_taken),
    .io_br_bus_br_target     (_ds_io_br_bus_br_target)
  );
  IE es (	// src/main/scala/stages/Top.scala:35:20
    .clock                     (clock),
    .reset                     (reset),
    .io_from_valid             (_ds_io_to_valid),	// src/main/scala/stages/Top.scala:34:20
    .io_from_bits_pc           (_ds_io_to_bits_pc),	// src/main/scala/stages/Top.scala:34:20
    .io_from_bits_alu_op       (_ds_io_to_bits_alu_op),	// src/main/scala/stages/Top.scala:34:20
    .io_from_bits_src1_is_pc   (_ds_io_to_bits_src1_is_pc),	// src/main/scala/stages/Top.scala:34:20
    .io_from_bits_src2_is_imm  (_ds_io_to_bits_src2_is_imm),	// src/main/scala/stages/Top.scala:34:20
    .io_from_bits_src2_is_4    (_ds_io_to_bits_src2_is_4),	// src/main/scala/stages/Top.scala:34:20
    .io_from_bits_gr_we        (_ds_io_to_bits_gr_we),	// src/main/scala/stages/Top.scala:34:20
    .io_from_bits_mem_we       (_ds_io_to_bits_mem_we),	// src/main/scala/stages/Top.scala:34:20
    .io_from_bits_dest         (_ds_io_to_bits_dest),	// src/main/scala/stages/Top.scala:34:20
    .io_from_bits_imm          (_ds_io_to_bits_imm),	// src/main/scala/stages/Top.scala:34:20
    .io_from_bits_rj_value     (_ds_io_to_bits_rj_value),	// src/main/scala/stages/Top.scala:34:20
    .io_from_bits_rkd_value    (_ds_io_to_bits_rkd_value),	// src/main/scala/stages/Top.scala:34:20
    .io_from_bits_res_from_mem (_ds_io_to_bits_res_from_mem),	// src/main/scala/stages/Top.scala:34:20
    .io_to_valid               (_es_io_to_valid),
    .io_to_bits_pc             (_es_io_to_bits_pc),
    .io_to_bits_gr_we          (_es_io_to_bits_gr_we),
    .io_to_bits_mem_we         (_es_io_to_bits_mem_we),
    .io_to_bits_dest           (_es_io_to_bits_dest),
    .io_to_bits_rkd_value      (_es_io_to_bits_rkd_value),
    .io_to_bits_res_from_mem   (_es_io_to_bits_res_from_mem),
    .io_to_bits_alu_result     (_es_io_to_bits_alu_result)
  );
  IM ms (	// src/main/scala/stages/Top.scala:36:20
    .clock                     (clock),
    .reset                     (reset),
    .io_from_valid             (_es_io_to_valid),	// src/main/scala/stages/Top.scala:35:20
    .io_from_bits_pc           (_es_io_to_bits_pc),	// src/main/scala/stages/Top.scala:35:20
    .io_from_bits_gr_we        (_es_io_to_bits_gr_we),	// src/main/scala/stages/Top.scala:35:20
    .io_from_bits_mem_we       (_es_io_to_bits_mem_we),	// src/main/scala/stages/Top.scala:35:20
    .io_from_bits_dest         (_es_io_to_bits_dest),	// src/main/scala/stages/Top.scala:35:20
    .io_from_bits_rkd_value    (_es_io_to_bits_rkd_value),	// src/main/scala/stages/Top.scala:35:20
    .io_from_bits_res_from_mem (_es_io_to_bits_res_from_mem),	// src/main/scala/stages/Top.scala:35:20
    .io_from_bits_alu_result   (_es_io_to_bits_alu_result),	// src/main/scala/stages/Top.scala:35:20
    .io_to_valid               (_ms_io_to_valid),
    .io_to_bits_pc             (_ms_io_to_bits_pc),
    .io_to_bits_gr_we          (_ms_io_to_bits_gr_we),
    .io_to_bits_dest           (_ms_io_to_bits_dest),
    .io_to_bits_res_from_mem   (_ms_io_to_bits_res_from_mem),
    .io_to_bits_alu_result     (_ms_io_to_bits_alu_result),
    .io_data_sram_we           (io_data_sram_we),
    .io_data_sram_addr         (io_data_sram_addr),
    .io_data_sram_wdata        (io_data_sram_wdata)
  );
  IW ws (	// src/main/scala/stages/Top.scala:37:20
    .clock                     (clock),
    .reset                     (reset),
    .io_from_valid             (_ms_io_to_valid),	// src/main/scala/stages/Top.scala:36:20
    .io_from_bits_pc           (_ms_io_to_bits_pc),	// src/main/scala/stages/Top.scala:36:20
    .io_from_bits_gr_we        (_ms_io_to_bits_gr_we),	// src/main/scala/stages/Top.scala:36:20
    .io_from_bits_dest         (_ms_io_to_bits_dest),	// src/main/scala/stages/Top.scala:36:20
    .io_from_bits_res_from_mem (_ms_io_to_bits_res_from_mem),	// src/main/scala/stages/Top.scala:36:20
    .io_from_bits_alu_result   (_ms_io_to_bits_alu_result),	// src/main/scala/stages/Top.scala:36:20
    .io_debug_wb_pc            (io_debug_wb_pc),
    .io_debug_wb_rf_we         (io_debug_wb_rf_we),
    .io_debug_wb_rf_wnum       (io_debug_wb_rf_wnum),
    .io_debug_wb_rf_wdata      (io_debug_wb_rf_wdata),
    .io_ws_to_rf_bus           (_ws_io_ws_to_rf_bus),
    .io_data_sram_rdata        (io_data_sram_rdata)
  );
  assign io_inst_sram_we = 4'h0;	// src/main/scala/stages/Top.scala:30:7, :33:20
  assign io_inst_sram_wdata = 32'h0;	// src/main/scala/stages/Top.scala:30:7, :33:20, :34:20, :35:20, :36:20, :37:20
  assign io_data_sram_en = 1'h1;	// src/main/scala/stages/Top.scala:30:7, :33:20, :34:20, :35:20, :36:20, :37:20
endmodule

